### ISSUE TITLE
Monochrome icons on tray

### ISSUE THREAD

**Issue by varlesh** [Bajoja/indicator-kdeconnect#1]
![screenshot from 2016-11-13 15-26-36](https://cloud.githubusercontent.com/assets/8083855/20246760/15672408-a9cf-11e6-8047-994cdd93e588.png)
Please change icons on tray. If you need help, i can draw new icons :)
I'm not found icon names for tray on source files (indicator use this icons from dbus?)

**Comment by varlesh** [comment]
And thx for your work :+1: , i'm already create PPA:
```
sudo add-apt-repository ppa:varlesh-l/indicator-kdeconnect
sudo apt update
sudo apt install kdeconnect indicator-kdeconnect
```

**Comment by Bajoja** [comment]
Great, i'm a fedora user, but i now a PPA will be useful for Ubuntu users.
At this time it use default icons that is provide by dbus, and dbus get them from "/usr/share/icons/hicolor/scalable/status/"
![screenshot from 2016-11-13 20-53-57](https://cloud.githubusercontent.com/assets/10621831/20248793/681673d4-a9e3-11e6-9684-2621b6f199dd.png)

But in the data folder have icons that was suppose to be the default icons, from the original project.
Personally i think that icons is ugly, maybe you can redraw them and we can think in one way to use them by default.

**Comment by varlesh** [comment]
Ok, im add **smartphone-connected** from  my theme - that working, icon apply from icon theme :)
Use only **smartphone-connected** icon or this used too:
**laptop-connected
tablet-connected**

**Comment by varlesh** [comment]
Now i'm draw 2 variants - **ubuntu-mono-dark** and and **ubuntu-mono-light** (because some users use white panels, some black)... and sizes 22px and 24px. Icon name will be as original. You like this variant?

**Comment by Bajoja** [comment]
Yes, if you have a laptop or a tablet with kdeconnect they will be apear on tray whit these icons.
For users that use this variant of theme make sense have these 2 variants, like in my case i prefer light ones.

**Comment by varlesh** [comment]
Fine, i'm draw!

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/20248986/2661a896-aa01-11e6-8ffa-6f6a1d999610.png)
Also dark version too. Wait new PR soon :)

**Comment by varlesh** [comment]
@Bajoja I see on your screenshot use **smartphone-disconnected** icon or **smartphone-trusted**.
This icons used too on tray? I can update and add new icons, if you need.

**Comment by varlesh** [comment]
Because i'm create only:

- laptop-connected
- smartphone-connected
- tablet-connected

If you need  **-trusted** and/or **-disconected** icons  - i can added.

**Comment by varlesh** [comment]
Add all icons https://github.com/Bajoja/indicator-kdeconnect/pull/3
Merge please

**Comment by Bajoja** [comment]
Yes these icons are used too.

**Comment by varlesh** [comment]
Ok, now all complete. I'm close, need update only CMakeFiles and add depend `ubuntu-mono`

**Comment by Bajoja** [comment]
@varlesh Build the new version on PPA please, ;)

**Comment by Bajoja** [comment]
@varlesh Build the new version on PPA please, ;)
