### ISSUE TITLE
feature : blacklist some notifications

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Bajoja/indicator-kdeconnect#103]
Hey guys, great work so far :)

I use Signal on my phone and Desktop. When I receive an unencrypted "regular" sms I get the notification on my computer thanks to KDE-Connect. But when I receive an encrypted Signal message I get two notifications on my computer : one from the Signal laptop app and one from KDE-Connect.

That would be great if we could blacklist some notifications on KDE-Connect based on the name (e.g. all notifications containing "signal" or something like that). Because I think it's an issue a lot of people can have given the number of apps that can be used to manage sms on desktop and computer at the same time.

Thank you :)

**Comment by Bajoja** [comment]
Hi, 
This kind of features have to be implemented on KDEConnect, and not indicator-kdeconnect, so make a feature request to KDEConnect developers.

**Comment by thiswillbeyourgithub** [comment]
Thank you, sorry, I'll close this

**Comment by Bajoja** [comment]
I dont have to apologize, it's just out of my possibilities
