### ISSUE TITLE
0.9.2 packages broken

### ISSUE THREAD

**Issue by KAMiKAZOW** [Bajoja/indicator-kdeconnect#104]
See https://build.opensuse.org/package/show/home:Bajoja/indicator-kdeconnect – all builds failed (and you left two 0.9.1 source code packages).

**Comment by Bajoja** [comment]
Strange, the build log say Sms.py not found, i will check that.

**Comment by Bajoja** [comment]
@KAMiKAZOW I'm not figuring out what's going on, if you can help me i will be greatfull.

**Comment by KAMiKAZOW** [comment]
Heh, the install script does not install Sms.py.

I simply commented out the %{_bindir}/indicator-kdeconnect/Sms.py line in the %files section and while https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW/indicator-kdeconnect/openSUSE_Factory/x86_64 complains about some installed but unpackaged files, none of them is Sms.py

**Comment by KAMiKAZOW** [comment]
Opened #109. Don't forget to put the changes in OBS as well. 😉
