### ISSUE TITLE
Bluetooth compatibility

### ISSUE THREAD

**Issue by sternj** [Bajoja/indicator-kdeconnect#105]
I have noticed that I cannot connect to my phone via Bluetooth on the default build on the repo. Does it work at all, and is there any way to build from source to support it?

**Comment by Bajoja** [comment]
Maybe is a KDEConnect Issue! Indicator-KDEConnect don't manage connections.

**Comment by andyholmes** [comment]
Just saw this the other day: https://www.reddit.com/r/linux/comments/6ggb36/kde_connect_works_over_bluetooth_now_please_help/

Basically need to build android from source yourself, doesn't work too well, no file transfers...

**Comment by Bajoja** [comment]
@sternj as @andyholmes say, you need to build the android app by yourself , if you want to use it.
