### ISSUE TITLE
SMS issue

### ISSUE THREAD

**Issue by rawdatalab** [Bajoja/indicator-kdeconnect#107]
Debian Stretch, compiled from source. Can't send SMS. Error msg: 

Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 422, in send_msg
    self.dbus.call_sync('sendSms', variant, 0, -1, None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/modules/kdeconnect/devices/30dbbc4ed930901/telephony' (41)

Please advise. Thank you.

**Comment by Bajoja** [comment]
>  No such object path  '/modules/kdeconnect/devices/30dbbc4ed930901/telephony'
That means the module to send sms is not active on your phone

**Comment by rawdatalab** [comment]
I have disabled and re-enabled the "Send SMS" plugin setting several times.

**Comment by andyholmes** [comment]
Try using [D-Feet](https://wiki.gnome.org/Apps/DFeet) to confirm that the module is loading correctly, it should be enabled on your phone and in KDE Connect settings.
