### ISSUE TITLE
Indicator Icon does not match with icon theme

### ISSUE THREAD

**Issue by rudevdr** [Bajoja/indicator-kdeconnect#108]
Indicator doesn't match with icon theme. Other panel indicators icon are dark but indicator-kdeconnect is green on XFCE Arch Linux. Using Papirus Light icon theme. It doesn't change on changing icon themes. Installed the indicator from AUR.

![panel](https://user-images.githubusercontent.com/19689713/33654789-19f9afc4-da69-11e7-87f5-447a1f0fd332.png)

It makes panel look less attractive.

**Comment by Bajoja** [comment]
Ok, I will check that.

**Comment by Bajoja** [comment]
Seems the name of the icons change (When indicator-kdeconnect ask for the icon is returned "smartphoneconnected", but before it was return "smartphone-connected"), so i change the name of the icons on the source.
I think the Papirus have to change them too.

**Comment by varlesh** [comment]
Fixed on Papirus
