### ISSUE TITLE
Send SMS from chosen default SMS app

### ISSUE THREAD

**Issue by Fjodor42** [Bajoja/indicator-kdeconnect#110]
I don't know if this would be better reported to KDEConnect proper, but if so, please let me know.

Anyway, I have set Signal as my default SMS app, but when I send an SMS from the menu (or replies to one), the sent SMS is stored with the Android stock messaging app.

It would be great if the default SMS app on the phone could be somehow deduced, and used for sending - for an Android app to be able to be set as the default SMS app, I assume that it must respond to at least a subset of an SMS sending API.

**Comment by Bajoja** [comment]
KDEConnect manage that kind of settings, will be better report this to them.
