### ISSUE TITLE
Connect to file system over command line

### ISSUE THREAD

**Issue by bgeVam** [Bajoja/indicator-kdeconnect#112]
Hi, this must be possible somehow. As far as i see, the indicator calls the following command:

`shfs -d kdeconnect@192.168.0.23:/ /home/georg/.config/kdeconnect/3f3e473ad60f9705/kdeconnect_sftp/123 -p 1739 -f -F /dev/null -o IdentityFile=/home/georg/.config/kdeconnect/privateKey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=ssh-dss -o password_stdin`

What is the password asked for in stdin, is it the one the private key was generated with?

Anything else i need to establish a connection?

Background: I want to sync my music over wifi

**Comment by andyholmes** [comment]
It's unlikely you'll be able to accomplish this. Basically what happens is KDE Connect sends the phone a request to start browsing, the phone responds by starting a SFTP server and replying with a randomly generated password (username is always kdeconnect) and a port (between 1739-1764).

None of that is actually exposed outside of KDE Connect though, so there's no way to intercept the password or port and use them.

**Comment by bgeVam** [comment]
Thanks for the clarification. I admit this is a bit disappointing, as kdeconnect-cli has no option as the "Browse Device" of the indicator. The "Browse Device" section of the indicator results in no action on my system (elementary OS). It worked right after installation though. If you want I can file a separate issue for this and we close this one for now?

**Comment by Bajoja** [comment]
Yes, put it on a separate issue, thanks.
