### ISSUE TITLE
Duplicate SMS Notifications

### ISSUE THREAD

**Issue by kbeanblossom** [Bajoja/indicator-kdeconnect#113]
I have been getting at least two (sometimes up to four) notifications for each SMS I get.

 
I tried uninstalling the app on my phone, and here is where it gets interesting. I gave the app notification access and did a test SMS, and I only got one notification like I'm supposed to. When I get the app Send SMS permissions is when I start getting multiple notifications for the same SMS. Even if I revoke the SMS permission on the Android app, I only get one notification, so it has to be something with the phone permission.

Running Elementary OS 0.4.1 Loki
Indicator-KDEConnect version: 0.9.3-1~webupd8~xxenial0

Phone is a Samsung Galaxy S8+ running Android 7.0
KDE Connect application is installed and updated.

**Comment by andyholmes** [comment]
You should accept any new permissions with the latest KDE Connect android app, and force-close/restart it. See also here: https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/49

**Comment by Bajoja** [comment]
I recomend the @andyholmes tip.

**Comment by PocketSam** [comment]
I've had a same problem, every time I've recieved SMS I saw 13 notifications. Clearing all app info on Android and re-registering with a KDE Connect solved the problem. Also I'm using MIUI, so I've had to allow all application background activity and autorun after application reset.
