### ISSUE TITLE
Browse device

### ISSUE THREAD

**Issue by andrewhq** [Bajoja/indicator-kdeconnect#114]
I could get browse device to work by enabling 'Show device directories:' in 'KDE Indicator Settings' but I am having this issue:

'Browse device' only works **once** ( pop up a nautilus window to '/run/user/1000/<id>/storage/emulated/0' and on **second** try it pop up a window to '/run/user/1000/<id>/storage/emulated/0/DCIM/Camera' ) and after that it **fails to open new windows**. If the 'Show device directories:' option is unchecked and checked again in KDE Indicator Settings it works again.

I am running Solus with Budgie DE and KDE Connect 1.2.1-9 and indicator-kdeconnect compiled from source. Everything else works as expeceted.

**Comment by Bajoja** [comment]
Hi, sorry for the late response, you try to open manualy with one slash after '/1000' ?

**Comment by andrewhq** [comment]
Yes. If I open /run/user/1000/41234234234/storage/emulated/0 manually it works.

**Comment by Bajoja** [comment]
Ok, i will check what is going on.

**Comment by Bajoja** [comment]
This topic should be resolved with the last commit

**Comment by Skylead** [comment]
Can we get a release tagged with this fix?
