### ISSUE TITLE
[Flatpak] cannot connect to KDE  Connect  DBus Service

### ISSUE THREAD

**Issue by alex285** [Bajoja/indicator-kdeconnect#115]
i downloaded it from Flathub, but when i tried to start it
```
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
grep: /app/etc/xdg/autostart/kdeconnectd.desktop: No such file or directory

** (indicator-kdeconnect:3): CRITICAL **: string_substring: assertion '_tmp12_ <= _tmp13_' failed

(indicator-kdeconnect:3): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed

(indicator-kdeconnect:3): GLib-GIO-CRITICAL **: g_file_query_exists: assertion 'G_IS_FILE(file)' failed
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

```

Flatpak version: 0.11.1 on Ubuntu 18.04
Commit: b58a3eade064109b4b2808aed05279d9da3137c12644dd7349cb306e36cf8ef5

**Comment by alex285** [comment]
oops, it needs the actual KDE Connect! sorry!

**Comment by milosb793** [comment]
> oops, it needs the actual KDE Connect! sorry!

Hey, I got the same problem. What does it mean `it needs the actual KDE Conenct`?

**Comment by Marukesu** [comment]
The flatpak package comes only with the indicator, the KDE connect needs to be installed from another Flatpak or in the system

**Comment by webdott** [comment]
i have the same problem. Please how do i fix this
I use Ubuntu 18.04

**Comment by milosb793** [comment]
> i have the same problem. Please how do i fix this
> I use Ubuntu 18.04

Hey, I think I've installed it with: `sudo apt install kdeconnect`

**Comment by webdott** [comment]
> > i have the same problem. Please how do i fix this
> > I use Ubuntu 18.04
> 
> Hey, I think I've installed it with: `sudo apt install kdeconnect`

I tried that...it dosen't seem to start up whenever i run the application
