### ISSUE TITLE
I receive two notifications when this is running

### ISSUE THREAD

**Issue by maelodic** [Bajoja/indicator-kdeconnect#119]
It looks like I'm getting a notification from both kde-connect and indicator-kdeconnect when I have this running. I do not have KDE-Connect in my system tray, and I only have indicator-kdeconnect running on startup. Any ideas on how to remove the double notification?

I'm using Dunst, i3, and polybar if that makes a difference.

**Comment by Bajoja** [comment]
Well, indicator-kdeconnect not send phone notifications, its managed by KDEConnect, so you have to report it to KDEConnect developers.
