### ISSUE TITLE
Not show translate on FirstTimeWizard

### ISSUE THREAD

**Issue by varlesh** [Bajoja/indicator-kdeconnect#12]
i open PR for fix PO-files, but not working :(
More dialog not showing:
![2016-12-13 02-30-38](https://cloud.githubusercontent.com/assets/8083855/21119581/af5a4fb2-c0dc-11e6-91e4-000ab7aa3a9d.png)
![2016-12-13 02-31-17](https://cloud.githubusercontent.com/assets/8083855/21119580/af5a3fd6-c0dc-11e6-816f-a9624bb03a52.png)
![2016-12-13 02-32-12](https://cloud.githubusercontent.com/assets/8083855/21119582/af6344aa-c0dc-11e6-9142-2cf094d978c4.png)
Need check sources and PO files...

**Comment by varlesh** [comment]
Maybe it's help you - build log:
https://launchpadlibrarian.net/297925164/buildlog_ubuntu-xenial-amd64.indicator-kdeconnect_0.4ubuntu16.04git20161213_BUILDING.txt.gz

**Comment by varlesh** [comment]
My PR https://github.com/Bajoja/indicator-kdeconnect/pull/11 not fixed this... i don't know why?
@Bajoja Steeven how emulate FirstTimeWizard with installed indicator-kdeconnect, it's possible?

**Comment by Bajoja** [comment]
Ok, something is wrong with the translation, because portuguese language is working on my computer.
![1](https://cloud.githubusercontent.com/assets/10621831/21125474/e63837be-c0dd-11e6-9412-e90330acb937.png)
![2](https://cloud.githubusercontent.com/assets/10621831/21125475/e98c51d4-c0dd-11e6-84b6-d327207eb0c2.png)
![3](https://cloud.githubusercontent.com/assets/10621831/21125482/ec03bf10-c0dd-11e6-96d7-bfef92d3e9ed.png)

**Comment by Bajoja** [comment]
@varlesh to emulate the FirstTimeWizard follows the following steps:
-> Unpair the device on your phone;
-> Open system monitor and kill ''indicator-kdeconnect'' and ''kdeconnect'' process;
-> ctrl+h on your home folder to see hidden files, go to ''.config/kdeconnect/'' folder and delete every file there.
-> then go to ''.config/autostart/'' folder and delete ''indicator-kdeconnect.desktop'' file;

execute indicator-kdeconnect again and FirtTimeWizard will appear.

**Comment by Bajoja** [comment]
I make a new commit that fix it for me, check if it work for you.


![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/10621831/21126588/2d69379e-c0e5-11e6-82c1-fefcd9c52fba.gif)

**Comment by varlesh** [comment]
Fine, thx :+1: I'm update PPA

**Comment by varlesh** [comment]
All fine and showing, big thx Steeven!
