### ISSUE TITLE
No popup on browse files

### ISSUE THREAD

**Issue by rudevdr** [Bajoja/indicator-kdeconnect#121]
Everything was working fine until I tried to change file manager to view device's files from Thunar.desktop to ranger.desktop in `~/.config/mimeapps.list`. Now this error keeps showing up in terminal when I try to browse files:
`(indicator-kdeconnect:31873): GLib-GIO-WARNING **: couldn't find a terminal, falling back to xterm`.

I tried reverting changes back to Thunar, where everything was working fine, but I still get same error.

I think the issue can be solved by deleting the configs of indicator-kdeconnect but I don't know where are they.

**Comment by Bajoja** [comment]
> couldn't find a terminal

Seems you don't have a default terminal setted, check how to set it.

**Comment by rudevdr** [comment]
I have xterm installed and set as default terminal but on browsing device xterm opens and closes immediately.

![test](https://user-images.githubusercontent.com/19689713/38316735-ff8f14ec-3848-11e8-9c11-2a7bcc707e34.gif)

**Comment by andyholmes** [comment]
Probably what you need to do is use `xdg-mime` or `gvfs-mime` to set the handler for directories, instead of editing them manually:

    $ xdg-mime default Thunar.desktop inode/directory
    $ gvfs-mime --set inode/directory Thunar.desktop

The Arch Wiki has a pretty extensive page on this: https://wiki.archlinux.org/index.php/Default_applications

**Comment by rudevdr** [comment]
@andyholmes Thank You! That did it.
