### ISSUE TITLE
KDE Connect indicator blocks Nautilus

### ISSUE THREAD

**Issue by QkiZMR** [Bajoja/indicator-kdeconnect#127]
When indicator is active and I try to copy file (RMB on file and click on Copy) I can't use Nautllus for few seconds. When I disable indicator everything works fine, without locking Nautilus.

**Comment by Bajoja** [comment]
What is your nautilus version?

**Comment by Bajoja** [comment]
Old nautilus versions, block with dbus, and kdeconnect send now will start to work with dbus, so i recomend you to use the last source on releases.

**Comment by QkiZMR** [comment]
You mean a new version of Nautilus or a new version of kdeconnect?

**Comment by Bajoja** [comment]
I ask for nautilus version, and referer kdeconnect send nautilus extension will not work well on old versions of nautilus

**Comment by QkiZMR** [comment]
If I will install new Gnome it should work? Probably I can't update Nautilus without updating Gnome itself.

**Comment by Bajoja** [comment]
So, I recommend you to use the [0.9.4]( https://github.com/Bajoja/indicator-kdeconnect/releases/tag/0.9.4) version.

**Comment by Bajoja** [comment]
I will roll back the old way that this work.

**Comment by QkiZMR** [comment]
but I'm using 0.9.4 version from webupd8 ppa.

**Comment by QkiZMR** [comment]
I downloaded the source code from GitHub, used master branch, compiled and run. Problem still persists.

**Comment by Bajoja** [comment]
KdeConnect it self, now have a application to send from nautilus, that app lock the nautilus, check if you  have it on nautilus extension folder.

**Comment by QkiZMR** [comment]
Do you know where this nautilus extension folder is located?

**Comment by Bajoja** [comment]
(y)
