### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by piomiq** [Bajoja/indicator-kdeconnect#129]
I typed first part of contact name in "SMS Send" dialog, clicked refresh button and in my browser (Opera) I got message like in subject. In address bar I saw strange url like:
openurl%28https//accounts.google.com/o/oauth2/v2/auth
Opera also inserted on begin "http://" string.
I checked with version 0.9.4 and git (today).
Note that part of contact name I tried to find I have in Google contacts.
After installation application KDE Connect on my phone I allowed it on all what it asked.

**Comment by Bajoja** [comment]
You should be redirect to https://accounts.google.com/signin/oauth/oauthchooseaccount
That address is converted, test on another broswer and test it again.

**Comment by piomiq** [comment]
Usage your URL shows me error 400 (in Firefox and Opera). Opera this is my default web browser. 

Anyway. I set default browser as Firefox and I was able to authorise KDE Connect to use contacts in Google. I'm not sure if you warn that this application doesn't work with Opera.

**Comment by Bajoja** [comment]
My URL was only a example, and not the real link, and the conclusion is that opera not work with this.
