### ISSUE TITLE
Use symbolic icons instead of current ones

### ISSUE THREAD

**Issue by MrSadnes** [Bajoja/indicator-kdeconnect#13]
Use `smartphone-connected-symbolic` and `smartphone-disconnected-symbolic` to keep only one version of the icons for light and dark desktops avoiding some design problems like these
![captura de tela de 2016-12-18 16 11 58](https://cloud.githubusercontent.com/assets/21296444/21295506/b247c140-c53d-11e6-9f9d-22ae0d88b63b.png)
![captura de tela de 2016-12-18 16 11 15](https://cloud.githubusercontent.com/assets/21296444/21295507/b248f11e-c53d-11e6-99a1-c0865390888e.png)

**Comment by varlesh** [comment]
It's impossible, because pantheon not colorize 3-d party apps on tray.
Create icon for your self, on Ubuntu all worked fine!
![image](https://cloud.githubusercontent.com/assets/8083855/21295580/9e43f5b8-c571-11e6-8190-af95f695602b.png)

**Comment by varlesh** [comment]
This icons use for Gnome and Cinnamon:
- computer-symbolic
- laptop-symbolic
- smartphone-symbolic
- tablet-symbolic

This icons used for Ubuntu and eOS:
- laptop-connected
- laptop-disconnected
- laptop-trusted
- smartphone-connected
- smartphone-disconnected
- smartphone-trusted
- tablet-connected
- tablet-disconnected
- tablet-trusted

**Comment by MrSadness** [comment]
in Loki (0.4), eOS use symbolic icons.
![captura de tela de 2016-12-18 16 39 20](https://cloud.githubusercontent.com/assets/21296444/21295644/ab8dafba-c540-11e6-9c8f-9867bf07903f.png)

**Comment by varlesh** [comment]
Also for Cinnamon and gnome use 16px icons size. But for Pantheon use 24px... you have big symbolic icon because use 16px on 24px tray.
@Bajoja I'm not understand why not use NOT symbolic icons on Pantheon?
@MrSadness When you change icon theme to ubuntu-mono-dark icon changed on tray?
Use this icons?
![image](https://cloud.githubusercontent.com/assets/8083855/21295646/0e558a1e-c573-11e6-828d-b8815ce476c5.png)

**Comment by varlesh** [comment]
> in Loki (0.4), eOS use symbolic icons.

But you see this not worked for 3-d party apps, because libbappindicator not have this option

**Comment by varlesh** [comment]
@Bajoja How this worked? If icon smartphone-connected not available use smartphone-symbolic or another method?

**Comment by MrSadness** [comment]
@varlesh yes, ubuntu-mono works. but, the rest uses hicolor icons. now i take the elemntary phone icon and rename her to smartphone-connected and work.

**Comment by varlesh** [comment]
You can try this variant:
```
sudo cp /usr/share/icons/ubuntu-mono-dark/status/24/smartphone* /usr/share/icons/elementary/status/24/
```

**Comment by varlesh** [comment]
we not create elementary icons for kdeconnect because we must add depend elementary-icon-theme - it's not needed for Gnome, Cinnamon, Ubuntu and other DE

**Comment by Bajoja** [comment]
@varlesh if it not available it uses the default theme icons, for the system.

**Comment by varlesh** [comment]
@Bajoja Ok, fine.
@MrSadness you can copy this icons (24px) on elementary icon theme folder from ubuntu-mono-dark or create new icons for tray:
```
laptop-connected
laptop-disconnected
laptop-trusted
smartphone-connected
smartphone-disconnected
smartphone-trusted
tablet-connected
tablet-disconnected
tablet-trusted
```

**Comment by Bajoja** [comment]
@MrSadness For now this is the best option, until we found a solution.
@varlesh i think is good idea create icons for elementary, because a lot of people use it, and we don't need to add a depends of ..., just copy the icons to icons folder, and they occupy a little space that nobody will care.

**Comment by varlesh** [comment]
Ok, i'm create version for eOS, but colorize option not possible, because it's specific DE tool and not worked for 3-d party apps.

**Comment by Bajoja** [comment]
Ok, thanks.

**Comment by varlesh** [comment]
done
![image](https://cloud.githubusercontent.com/assets/8083855/21296119/3d086bf6-c57d-11e6-8b0d-aa96df48caa9.png)

**Comment by Bajoja** [comment]
@MrSadnes Check if the new icons work, open this issue for any problems.

**Comment by MrSadnes** [comment]
Ok, the icons are great! But only on dark wallpapers, on light wallpapers the icon is white while the rest is black.

![wow](https://cloud.githubusercontent.com/assets/21296444/21298366/78ca2626-c577-11e6-90a0-e16f3ae49ce8.png)
![erro](https://cloud.githubusercontent.com/assets/21296444/21298369/7c653fe6-c577-11e6-91ef-197cf75b6bf2.png)


But I fixed this problem :)

![wow-sysmbolic](https://cloud.githubusercontent.com/assets/21296444/21298375/8db0e14c-c577-11e6-9463-6ead470d301a.png)
![erro-symbolic](https://cloud.githubusercontent.com/assets/21296444/21298376/913794d2-c577-11e6-884f-c1ab26b4c1bb.png)


It is necessary to add _`+ "-symbolic"`_ to **device.icon_name** in [DeviceIndicator.vala](https://github.com/Bajoja/indicator-kdeconnect/blob/master/src/DeviceIndicator.vala) and rename the icons according (smartphone- * status * -symbolic) in both elementary and ubuntu-mono

**Comment by varlesh** [comment]
Now you icons blurred and bigger, because you use 16px-symbolic icons on 24px tray!
It's not universal variant and not worked for non Vala apps - Qt, Electron and etc... because elementary icon theme not supported 3-d party apps:
https://github.com/elementary/icons#third-party-brand-preservation

@Bajoja I'm not recommend add this fix to master branch because Gnome, Cinnamon and other DE use 16px symbolic icons by default, but  Patheon use 24px. Icons will be blurred or very tiny.

**Comment by MrSadnes** [comment]
@varlesh this icon is a place holder i take it from elementary symbolic icons for devices (not status)

**Comment by varlesh** [comment]
@MrSadnes you not understand me...
Steeven say if icon smartphone-connected not available on icon theme use smartphone-symbolic.

BUT you see you icon blurred and bigger, because have another size. You icon have 16px size, but for Pantheon use only 24px for tray!
We can't resize smartphone-symbolic from 16px to 24px for elementary only because icon will be blurred and very tiny on Gnome and Cinnamon!
Also devices symbloic icons available an Gnome and Pantheon but not fully - not have icon laptop-symbolic for example and again problem with different sizes.

**Comment by Bajoja** [comment]
I did not know that this in elementary was a mess, really now that I've been reading to third party applications does not work properly.

@MrSadnes i can't add '+ "-symbolic"' to the code for now because the icons that we use will not work.

@varlesh you recommend to undo the commit?

**Comment by varlesh** [comment]
> @varlesh you recommend to undo the commit?

No, icon worked but not applied color modification. Pnatheon change symbolic icons on if use light wallpaper - it's specific DE option.
Now i understand if icon use `-symbolic` suffix - pantheon apply another color for icon. But symbolic icons now installed to hicolor theme, but elementary icon theme not have option `inherits` for use hicolor icon theme or gnome and etc...
Now we can add suffix `-symbolic`  ubuntu-mono-dark and elementary icons and change sources for right work. Or modify sources for elementary only, but i don't know how this will be worked...

**Comment by varlesh** [comment]
@Bajoja `smartphone-connected`, `smartphone-trusted` and other icon NAMES used from kdeconnect? It's hardcoded icon names or not?

**Comment by MrSadnes** [comment]
@varlesh According to the gnome website

> Symbolic icons are usually low color or monochrome and intended to match the foreground font color

and hicolor,gnome,adwata symbolic icons works too.

**Comment by varlesh** [comment]
Now we have 3 variants icons for indicator-kdeconnect - all icons worked and looked fine, but on Pnatheon not apply color modification if you change wallpaper to light tone, because elementary icons not have suffix `-symbolic`

**Comment by varlesh** [comment]
@MrSadnes On indicator-kdeconnect used different icon names for appindicator and gnome!
For appindicator:
laptop-connected
laptop-disconnected
laptop-trusted
smartphone-connected
smartphone-disconnected
smartphone-trusted
tablet-connected
tablet-disconnected
tablet-trusted

For Gnome:
computer-symbolic
laptop-symbolic
smartphone-symbolic
tablet-symbolic

**Comment by varlesh** [comment]
I'm confused :laughing: 
@Bajoja Please tell how this worked? I see for ubuntu-mono available 9 icons, but symbolic have 4 icons, Why?

**Comment by varlesh** [comment]
trusted and disconnected not used for Gnome or how? Or maybe use colors for GTK/Shell theme?

**Comment by Bajoja** [comment]
@varlesh, this things of icon are making me confused too.

But what happens is this, symbolic icons are monochromatic icons that just appear on the indicator to represent the device user are using, smartphone, computer, laptop or tablet, this why 4 icons only.   
I modify indicator-kdeconnect to work with the 9 icons, that allows the icons change case they are trusted or untrusted, because is more simple distinguish your devices (trusted) from those that are not (untrusted).

In my school a lot of devices have kdeconnect, so imagine when i connect to the WIFI the number of devices that appear on my indicator, the only way to know what indicator is mine is have the trusted ones (normal icons) and the untrusted(red icons).

**Comment by varlesh** [comment]
@Bajoja symbolic icons use colors from Gnome Shell theme for disconnected and trusted status?

**Comment by Bajoja** [comment]
@varlesh do not use.

**Comment by varlesh** [comment]
@Bajoja We can modify sources for Pantheon? Need add '-symbolic' suffix for all icons ubuntu-mono and elementary.

**Comment by varlesh** [comment]
i mean this icon names:
```
laptop-connected-symbolic
laptop-disconnected-symbolic
laptop-trusted-symbolic
smartphone-connected-symbolic
smartphone-disconnected-symbolic
smartphone-trusted-symbolic
tablet-connected-symbolic
tablet-disconnected-symbolic
tablet-trusted-symbolic
```

**Comment by Bajoja** [comment]
@varlesh it not use symbolic icons, it use the scalable ones.

**Comment by Bajoja** [comment]
if we modify the sources i don't know if it will work for systems not use symbolic icons like mine.

**Comment by varlesh** [comment]
Yes and Pantheon use another size for symbolic icons on panel... OMG it's crazy - very many DE's and standards :)

**Comment by varlesh** [comment]
@MrSadnes i think better disable this option for dark icons on tray because it's very strange method...
Other tray apps, for example telegram, skype, vlc and etc will be look ugly too.

**Comment by Bajoja** [comment]
@varlesh yah, it's a lot of standards, so it's not easy to help everyone. 

Some people have to do like me, replace them manually.

**Comment by MrSadnes** [comment]
Ok then I will keep the code on my pc since it is working in the elementary (the other themes carry the symbolic icons but not the indicator) and try to find a way to use both symbolic and scalable

**Comment by Bajoja** [comment]
@MrSadnes i will. ;)

**Comment by MrSadnes** [comment]
Ok, I finally figure out how the icons work ... and I did not do anything XD

1. yes, when **`+ "-symbolic"`** is added to the indicator, scalable icons continue to work.

2. I created a few more simple icons for the **Adwaita/gnome theme** (they are symbolic because it is the default theme) to make the indicator more complete being these inherits for most themes

images:
Elementary (Symbolics)
 ![elementary-black](https://cloud.githubusercontent.com/assets/21296444/21474211/2c426318-cb03-11e6-9538-b74c98d83ec3.png) ![elementary-white](https://cloud.githubusercontent.com/assets/21296444/21474210/2a2d9e9e-cb03-11e6-92f3-09b248984de3.png)

Ubuntu-mono (Scalables)
![ubuntu-mono-dark-black](https://cloud.githubusercontent.com/assets/21296444/21474227/5e16ec24-cb03-11e6-84a2-1c394c875f17.png)![ubuntu-mono-dark-white](https://cloud.githubusercontent.com/assets/21296444/21474228/612803bc-cb03-11e6-9687-02bc9126335d.png)
![ubuntu-mono-light-black](https://cloud.githubusercontent.com/assets/21296444/21474233/6932a7c4-cb03-11e6-8622-9a392682d247.png)![ubuntu-mono-light-white](https://cloud.githubusercontent.com/assets/21296444/21474234/6b5af510-cb03-11e6-9967-b0fd6812e0ec.png)

Adwaita/Gnome(Symbolics)
![adwaita-black](https://cloud.githubusercontent.com/assets/21296444/21474251/bb5656f4-cb03-11e6-9d97-cd7df4fc7210.png)![adwaita-white](https://cloud.githubusercontent.com/assets/21296444/21474252/bcc5ce48-cb03-11e6-9c9c-1a0004450e79.png)
![adwaita](https://cloud.githubusercontent.com/assets/21296444/21474254/bf4cd4cc-cb03-11e6-8865-de404d5a4c3b.png)

This Only works with  `-symbolic` suffix becasue of the default fallabacks are:
{
smartphone-connected-symbolic
smartphone-connected
smartphone
}

**Comment by Bajoja** [comment]
Ok, i will check this, can you zip and upload this icons? I will need them for test.

**Comment by ov3rcod3** [comment]
here [https://drive.google.com/file/d/0B4vfO-ZjOuErX1JGVDIxT0MtU2M/view?usp=sharing](url)

**Comment by MrMarukesu** [comment]
I made [this PR](https://github.com/Bajoja/indicator-kdeconnect/pull/41) for the support of symbolic icons that allowed the integration of the indicator to themes that use it
