### ISSUE TITLE
Desktop freeze when sending files from the phone

### ISSUE THREAD

**Issue by pshem** [Bajoja/indicator-kdeconnect#130]
I've got a problem with file operations. Mounting the file system doesn't work, I just get an empty folder. Sending files from the phone to the computer fares even worse, with the computer freezing. Moving the mouse doesn't work, keyboard doesn't work, remote input from KDE Connect doesn't work. The phone claims that sending is in progress, but after 60s nothing changes, so I just hard reboot the computer. This happened twice in a row, so it's definitely replicable. The file was relatively small, a 4 MB photo.

The host OS is Peppermint 8, an Ubuntu 16.04 derivative and KDE Connect Indicator is installed via the webupd8 PPA. The WiFi network uses the same SSID for 2.4GHz and 5GHz, and both the phone and laptop use both bands according to their needs. Sending files and mounting the filesystem used to work ~6 months ago, in autumn. I've tried reinstalling the mobile application and the issue persists. Any suggestions on how I can get the logs from the freeze and assist with debugging this issue are welcome.

Version:
```
pshem@PiDell $ apt search kdeconnect
indicator-kdeconnect/xenial,now 0.9.4-1~webupd8~xenial0 amd64 [installed]
  Indicator for KDE Connect

kdeconnect/xenial,now 1.0.3-0ubuntu2~webupd8~xenial1 amd64 [installed,automatic]
  connect smartphones to your KDE Plasma Workspace
```
Mobie app: KDE Connect 1.8.4 from Google Play, Android 7.1.1

Desktop:
```
pshem@PiDell ~ $ inxi -Fz
System:    Host: PiDell Kernel: 4.13.0-41-generic x86_64 (64 bit) Desktop: N/A
           Distro: Peppermint Eight
Machine:   System: Dell (portable) product: Inspiron 15 7000 Gaming
           Mobo: Dell model: 065C71 v: A00 Bios: Dell v: 1.6.0 date: 03/27/2018
CPU:       Quad core Intel Core i7-7700HQ (-HT-MCP-) cache: 6144 KB 
           clock speeds: max: 3800 MHz 1: 2459 MHz 2: 3038 MHz 3: 3368 MHz
           4: 3062 MHz 5: 3076 MHz 6: 2626 MHz 7: 3058 MHz 8: 3115 MHz
Graphics:  Card-1: Intel Device 591b
           Card-2: NVIDIA Device 1c8c
           Display Server: X.Org 1.19.5 driver: nvidia
           Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 384.130
Audio:     Card Intel Device a171 driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.13.0-41-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169
           IF: enp2s0 state: down mac: <filter>
           Card-2: Intel Wireless 3165 driver: iwlwifi
           IF: wlp3s0 state: up mac: <filter>
Drives:    HDD Total Size: 1256.3GB (14.3% used)
           ID-1: /dev/sda model: Micron_1100_SATA size: 256.1GB
           ID-2: /dev/sdb model: TOSHIBA_MQ01ABD1 size: 1000.2GB
Partition: ID-1: / size: 46G used: 17G (38%) fs: ext4 dev: /dev/sdb3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 46.0C mobo: N/A gpu: 44C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 241 Uptime: 2:15 Memory: 1433.5/15906.8MB
           Client: Shell (bash) inxi: 2.2.35 
```

**Comment by Bajoja** [comment]
Seems to be a KDEConnect problem, and your KDEConnect version seems to be outdate, try to update it fisrt.

**Comment by pshem** [comment]
Oh. The webupd8 repository is out of synch with newer KDE Connect versions :-1:

**Comment by Bajoja** [comment]
Yah, it has been abandoned.

**Comment by pshem** [comment]
Do you think it makes sense to add a note in the readme that the version from webupd8 doesn't support file transfers, or is it not worth it since most people who use PPAs have updated to Bionic already?

**Comment by Bajoja** [comment]
Ok, I will add, and we are looking for a new deb maintainer
