### ISSUE TITLE
Does the indicator work on xfce?

### ISSUE THREAD

**Issue by benburrill** [Bajoja/indicator-kdeconnect#131]
I got the impression that the indicator was supposed to work on xfce, but after installing it from the AUR (indicator-kdeconnect-git) and running indicator-kdeconnect in a terminal, I saw no indicator appear despite being paired to a device.  Since I wasn't sure if AppIndicators showed up in the notification area panel plugin, I installed the xfce indicator plugin which claims to support unity indicators, but it just says "No indicators".

So I'm not sure if I'm doing something wrong, the package doesn't support xfce, or if its a bug.

**Comment by Bajoja** [comment]
Yes, it works, so open your system management and kill if exists a instance of indicator-kdeconnect, the execute indicator-kdeconnect from terminal and show me the output.

**Comment by benburrill** [comment]
```
$ indicator-kdeconnect
** Message: 14:05:53.646: KDEConnectManager.vala:35: KDE Connect daemon found
** Message: 14:05:53.647: KDEConnectManager.vala:43: Devices file not creates
** Message: 14:05:53.647: Device.vala:17: device : /modules/kdeconnect/devices/b302ba73823ef77d
** Message: 14:05:53.657: DeviceIndicator.vala:375: signal received
** Message: 14:05:53.658: Device.vala:695: Founded Directories 0
** Message: 14:05:53.663: InOut.vala:19: File path exist '/tmp/indicator_kdeconnect_devices'

** Message: 14:05:53.663: InOut.vala:31: Status found on file - lgl33l-ben : b302ba73823ef77d


```

**Comment by Bajoja** [comment]
Your phone is connected?

**Comment by benburrill** [comment]
Yeah, KDE Connect Settings says it's paired and I can send pings back and forth.

**Comment by Bajoja** [comment]
What is your version of KDEConnect and indicator-kdeconnect?

**Comment by benburrill** [comment]
KDE Connect: 1.3.0.  I got it from the Manjaro repositories.

indicator-kdeconnect: 0.9.4, commit 1634e54 (HEAD).  I got it from the AUR (indicator-kdeconnect-git).

**Comment by benburrill** [comment]
I should have tried this earlier, but I just logged out and back in again and tried running it again and it worked.  Sorry for bothering you.
