### ISSUE TITLE
not visible in tray when run as non root on ubuntu budgie 18.04

### ISSUE THREAD

**Issue by michallepicki** [Bajoja/indicator-kdeconnect#134]
I successfully paired my device using `indicator-kdeconnect` and I can get ping notifications (as well as send them after running `kcmshell5 kcm_kdeconnect`) but when running `kdeconnect-indicator` nothing shows up in notification icons area. The indicator shows only when run using `sudo`, but obviously I don't want to do that. Console output:
```
$ kdeconnect-indicator 
Gtk-Message: 09:31:06.232: Failed to load module "gail"
Gtk-Message: 09:31:06.240: Failed to load module "canberra-gtk-module"

** (kdeconnect-indicator:9480): WARNING **: 09:31:06.240: (../atk-adaptor/bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
```

edit: I installed `libgail-common` and `libcanberra-gtk-module` and now still nothing shows up in tray but there are no errors in terminal output - it's empty:
```
$ kdeconnect-indicator

```

**Comment by Bajoja** [comment]
I'm not  familiarised with Budgie, but tr to install "libatk-adaptor" too

**Comment by dmromanov** [comment]
I have the same issue on a similar system.
First launch of the app and pairing were successful, but now it does not launch.
 "libatk-adaptor" is installed in my system.

**Comment by michallepicki** [comment]
Can confirm, "libatk-adaptor" installed.

cc @fossfreedom (I know you'll probably go with building something on top of [mConnect](https://github.com/bboozzoo/mconnect) as mentioned in https://github.com/solus-project/budgie-desktop/issues/1439 but I getting this indicator working and playing with it may be useful)

**Comment by fossfreedom** [comment]
@michallepicki Ensure you have the appindicator applet added to your panel through budgie-settings.

Ubuntu Budgie and Solus-Project are both trying to encourage someone to step forward to create a budgie-applet for the community.  Currently trying to mentor two potential indie-devs to help here.  Cross-fingers.

**Comment by michallepicki** [comment]
@fossfreedom that was it, thank you!

**Comment by moeenio** [comment]
I know this project is dead, but I'm facing the same issue. I've installed libatk-adaptor, libgail-common and libcanberra-gtk-module, I have an AppIndicator applet in my panel. Compiled this from source following instructions from the INSTALL file. Nothing showing up even as sudo. Ubuntu 20.04.1 LTS.
