### ISSUE TITLE
switch from kdeconnect to mconnect or similar

### ISSUE THREAD

**Issue by fossfreedom** [Bajoja/indicator-kdeconnect#135]
Hi there,

  from your experience do you think it would be possible to get indicator-kdeconnect to use mconnect or similar rather than kdeconnect?

The reason for the question is that I'm interested if a GTK based desktop can avoid all the Qt based stuff from kdeconnect.

Would it be a complete rewrite and reimplementation?

**Comment by Bajoja** [comment]
Hi, no it's not complicated.
It need only a server, like gconnect, that send events to it via DBus. 
Indicator needs to change the signals that it subscribe to the new server signals, and rewrite some Dbus call methods.

**Comment by fossfreedom** [comment]
many thanks for the info.  much appreciated!

**Comment by Bajoja** [comment]
I analize the situation, I am not promising anything because cons may arise, but I will try, to implement over gconnect.
