### ISSUE TITLE
Unable to access KDE Connect System Settings

### ISSUE THREAD

**Issue by wesbarnett** [Bajoja/indicator-kdeconnect#137]
I'm on Arch Linux using dwm for my window manager. trayer is used for the system tray.

When I click on the menu item on the indicator icon entitled "Device Reachable and Trusted" nothing happens. The following is output to the terminal:

    ** Message: 17:03:30.200: DeviceIndicator.vala:124: Failed to execute child process “kcmshell5” (No such file or directory)

I was thinking this was how to open the KDE Connect System Settings. It seems like it might be trying to open up KDE Settings and since I'm not on KDE obviously fails.

**Comment by premek** [comment]
Try to install `kde-cli-tools` package. In debian it is installed as a dependency of `kdeconnect` package.

**Comment by Bajoja** [comment]
Check the answer of @premek
