### ISSUE TITLE
Make the dialog showing incoming sms and calls copyable and non-closable on click

### ISSUE THREAD

**Issue by felagund** [Bajoja/indicator-kdeconnect#138]
Showing SMS in a dialog is great. However, when I click anywhere on the dialog, it closes. Sometimes, I would like to copy the text in the dialog, which is impossible (especially when using dual-factor identification).

This is on Ubuntu 18.04. To make the indicator work under Unity, I installed also a version (0.9.4.1) from webup8, but I also have 1.3.1 from the repositories installed.

**Comment by premek** [comment]
I'd love this too. This is why I installed kdeconnect. But I cannot find out how to access the notifications. 

I'm not sure if we can change how they are displayed (are they displayed by kdeconnectd or indicator-kdeconnect?) 

Maybe it can be solved by listing them in the popup menu and copy on click or something. But I cannot even list my notifications with kdeconnect-cli.

**Comment by adnidor** [comment]
Are you referring to the notification or the dialog where you answer the SMS? 
If the former, this is controlled by unity and not something kdeconnect can control.
If the latter, I can copy text from there, could you post a screenshot to show the problem?

Note: I'm not a developer of kdeconnect or anything, I'm just trying to help

**Comment by felagund** [comment]
What Os and Desktop environment and which versions are you using?

**Comment by adnidor** [comment]
Arch Linux with i3 as window manager and dunst as notification daemon

**Comment by felagund** [comment]
I see. I think that might be it. I do not have my android phone on me until December (it is being repaired) so I cannot do the screenshot, but maybe you could provide yours?

**Comment by adnidor** [comment]
Sorry, I don't have an easy way to do that without leaking private information

**Comment by adnidor** [comment]
A SMS to myself doesn't trigger a notification, so I would have to find someone else, or use a web service, and to be honest that too much effort for me to put into something that's not really necessary

**Comment by premek** [comment]
Note for testing, restarting `kdeconnectd` re-displays all the notifications currently present on the phone to the PC again.

Just to make sure, I think the goal here is to be able copy a text of a notification (nothing to do with sms reply dialog). 
- E.g. you receive a SMS or any other message on the phone, 
- the notification is displayed and sent to the PC, 
- the notification is displayed on the desktop 
- and you want to select [a part of] the notification's text and paste it into a web browser for example.

The notifications are displayed by kdeconnectd (not a part of this project) so it would be better to solve this there or in the notification daemon. I use xfce4-notifyd and also tried dunst mentioned above and I'm not able to select text in them.

kdeconnectd could add a button labeled "copy" to the notification to copy the whole text. Maybe.

indicator-kdeconnect (this app) is notified about new notifications and could collect them and display them in the popup menu or in a window. Would that be usable?

Note: Also not a developer of kdeconnect or anything :)

**Comment by premek** [comment]
Oh, I just realised you can click "Reply" in the notification, select and copy the text of the original message there and then close the window...

Obviously works only for notifications that has the reply button

**Comment by Bajoja** [comment]
@premek, you can handle notifications via dbus

**Comment by Bajoja** [comment]
Seems Kdeconnect are developing a SMS Ui that can resolve the issue, let's wait and see

**Comment by premek** [comment]
> Kdeconnect are developing a SMS Ui

do you have any more info? thanks

**Comment by Bajoja** [comment]
You can found it, on KDEConnect repository.
