### ISSUE TITLE
Multiple indicator icons & can't browse my device

### ISSUE THREAD

**Issue by AmonM** [Bajoja/indicator-kdeconnect#140]
Hello,
*WARNING* I'm  a total noob when it comes to Linux. *WARNING*

OS:
Linux Ubuntu 18.04LTS

DESCRIPTION:
I have installed indicator-kdeconnect and kdeconnect.
My problem is that it shows me 3 indicator icons when I search in app menu. One is for SMS settings another one is new indicator that allows me to send SMS and the last one is the old indicator that throws error because I'm not using 

1.PROBLEM
Is there a way to get rid of the old indicator program?

![screenshot from 2018-10-26 13-31-49](https://user-images.githubusercontent.com/37686290/47563902-8b5cd600-d923-11e8-8017-da5650cee637.png)

2.PROBLEM
Also the new indicator doesn't let me browse my devices.. When I click on "Browse device" nothing happens. (at the begging it used to work 1. time, the 2. time it would open photos and 3. time nothing happened anymore -> now nothing happens even when I click on it for the first time after logging in)

Thank you very much in advance.

**Comment by Bajoja** [comment]
Hi,
2 - Check for another topics about this.

1- Try to uninstall the all of them and install again.
