### ISSUE TITLE
Can't browse my device → working only if I run indicator-kdeconnect-settings by terminal

### ISSUE THREAD

**Issue by lalincedeldeserto** [Bajoja/indicator-kdeconnect#142]
I can't browse my device unless I run the command "indicator-kdeconnect-settings" in the terminal, then I close the window "kdeconnect-indicator-settings" and I try again to browse my device. From this point on, it works correctly.
I'm using Linux Mint 19 Cinnamon with Nemo 3.8.6 as the file manager.

**Comment by premek** [comment]
I also had problems with browsing some times. I had to enable "Show device directories".

**Comment by Bajoja** [comment]
The only file manager that i don't have problems is that one from Linux Deepin

**Comment by lalincedeldeserto** [comment]
Sorry if I write only right now, I'm enjoying your app! :+1:
