### ISSUE TITLE
Attention Icon

### ISSUE THREAD

**Issue by Bajoja** [Bajoja/indicator-kdeconnect#143]
Need a Icon to represent Attention [(For example)](https://www.google.pt/search?q=icon+device+attention&source=lnms&tbm=isch&sa=X&ved=0ahUKEwij19rblsveAhVSLBoKHV0PBp0Q_AUIDigB&biw=1366&bih=672) to represent things like, pending pairing, battery low power, so if someone want to do this will be welcome.

@varlesh :smirk:

**Comment by varlesh** [comment]
[icons.tar.gz](https://github.com/Bajoja/indicator-kdeconnect/files/2636099/icons.tar.gz)

**Comment by Bajoja** [comment]
@varlesh perfect, can i submit to main repo, or you do a pull request?

**Comment by varlesh** [comment]
@Bajoja of course, you can submit

**Comment by varlesh** [comment]
fix opacity on Adwaita `*disconnected` icons. Sorry, my fault.
[icons.tar.gz](https://github.com/Bajoja/indicator-kdeconnect/files/2638108/icons.tar.gz)

**Comment by Bajoja** [comment]
Thanks
