### ISSUE TITLE
Filesystem mounting not working: "no matching host key type found."

### ISSUE THREAD

**Issue by tsjnachos117** [Bajoja/indicator-kdeconnect#144]
When I try to browse my phone, a file browser opens with an empty folder. None of the workarounds from bug #10 seem to help. In fact, I am filing this bug because I believe it to be a completely different bug.

According to /etc/mtab, the filesystem is not even mounted. 

When killing the kdeconnect daemon, and manually running it from the terminal, I got this:

```
kdeconnect.plugin.sftp: Mount device: "Samsung Galaxy S6"
kdeconnect.plugin.sftp: Created mounter
kdeconnect.plugin.sftp: Starting loop to wait for mount
kdeconnect.plugin.sftp: Unmount QObject(0x0)
kdeconnect.core: Converting IPv6 QHostAddress("::ffff:192.168.1.75") to IPv4 QHostAddress("192.168.1.75")
kdeconnect.plugin.sftp: Starting process:  "sshfs kdeconnect@192.168.1.75:/ /run/user/1000/dd5fe59cdd84f0d7 -p 1743 -s -f -F /dev/null -o IdentityFile=/home/tyler/.config/kdeconnect/privateKey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=ssh-dss -o uid=1000 -o gid=1000 -o reconnect -o ServerAliveInterval=30 -o password_stdin"
QDBusAbstractAdaptor: Cannot relay signal SftpPlugin::packetReceived(NetworkPacket): Unregistered input type in parameter list: NetworkPacket
kdeconnect.plugin.sftp: Process started
kdeconnect.plugin.sftp: "Samsung Galaxy S6" "Remote filesystem mounted at /run/user/1000/dd5fe59cdd84f0d7"
kdeconnect.plugin.sftp: stdout: "Unable to negotiate with 192.168.1.75 port 1743: no matching host key type found. Their offer: ssh-rsa\r\n"
kdeconnect.plugin.sftp: stdout: "read: Connection reset by peer\n"
kdeconnect.plugin.sftp: Process finished (exit code:  1 )
kdeconnect.plugin.sftp: "Samsung Galaxy S6" Remote filesystem unmounted
kdeconnect.plugin.sftp: Unmount KProcess(0x55d3e8995270)
fusermount: entry for /run/user/1000/dd5fe59cdd84f0d7 not found in /etc/mtab
kdeconnect.plugin.sftp: Destroy mounter
kdeconnect.plugin.sftp: Unmount QObject(0x0)
```
This appears to be an issue with ssh. KDEConnect explicitly tells ssh to use ssh-dss, which is obsolete, and should not be used. In fact newer versions of openssh refuse to use this cipher unless you explicitly tell it to. Instead, ssh-rsa should be used, as it's the only one that appears to be supported.

**Comment by andyholmes** [comment]
`Unable to negotiate with 192.168.1.75 port 1743: no matching host key type found. Their offer: ssh-rsa`

This means you've upgraded to the Android app v1.10 which dropped DSA encryption (deprecated) for RSA encryption. You need to upgrade KDE Connect on your desktop to >= 1.3.2.

**Comment by tsjnachos117** [comment]
@andyholmes: Hi. Unfortunately, I don't think I can do that. As far as I can tell, there are no versions for Ubuntu 18.04 other than 1.3.1. Scouring launchpad.net, I can't find anything, except one PPA whose package wouldn't install because the owner didn't seem to realize there was a package dependency issue.

**Comment by andyholmes** [comment]
Rik Mills has a PPA building from git that is probably your best bet right now:

https://launchpad.net/~rikmills/+archive/ubuntu/experimental

Probably the debian package from sid would work, or there's nightly flatpaks but I've tried neither:

https://packages.debian.org/sid/main/kdeconnect#pdownload
https://binary-factory.kde.org/job/Kdeconnect_flatpak/

Your best bet is to request a version bump on Launchpad, for whoever the package maintainer is.

**Comment by tsjnachos117** [comment]
Rik Mills' ppa requires a newer library (I don't remember which) than what is available. Likewise for the deb packages form Sid. I didn't know about the flatpaks, however.

**Comment by andyholmes** [comment]
@tsjnachos117 

Just heard about these for you:

https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports?field.series_filter=bionic
https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/ppa?field.series_filter=bionic

Not sure what the difference between the backports and updates PPA are, though

**Comment by Bajoja** [comment]
I belive your problem is the one that @andyholmes mentioned above.

**Comment by andyholmes** [comment]
I think those builds just showed up. Albert (main kdeconnect dev) sent a release email out, but apparently his emails were being blocked and he didn't realize so builds were delayed. Not sure if they'll be doing backports all the way to 16.04 though, but the PPA might still work since it should have all dependencies.

**Comment by andyholmes** [comment]
@Bajoja here I am on your bug tracker again :laughing:

**Comment by bastafidli** [comment]
On ubuntu 18.04 adding backports ppa and upgrading to kde connect 1.3.3 solved the problem

**Comment by Bajoja** [comment]
I will consider @bastafidli as a solution for the problem.

**Comment by Bajoja** [comment]
I will consider @bastafidli as a solution for the problem.

**Comment by shamoi** [comment]
https://code.launchpad.net/~rikmills/+recipe/kdeconnect-daily
