### ISSUE TITLE
Add libjson-glib-dev to dependencies

### ISSUE THREAD

**Issue by danilo-bc** [Bajoja/indicator-kdeconnect#146]
Just an additional to the Install instructions. Tried to build on Linux Mint 19 (Tara) and Meson complained about lack of json-glib-1.0.

`sudo apt install libjson-glib-dev`

solved the issue.

Thanks for the project!

**Comment by Bajoja** [comment]
Hi, thank you, can you submit a pull request for [installation info](https://github.com/Bajoja/indicator-kdeconnect/blob/master/INSTALL)?

**Comment by danilo-bc** [comment]
I'm quite new to the process, but I think I've done it the right way.

I'm not 100% sure the Fedora package is named `json-glib-devel`. I researched a little, but I have no friends using Fedora to check at the moment.

**Comment by Bajoja** [comment]
I'm not sure too, i don't use Fedora for a long time, but if not someone, will be fix.
