### ISSUE TITLE
[Minor] Typo on 'Show Remote Keybord'

### ISSUE THREAD

**Issue by danilo-bc** [Bajoja/indicator-kdeconnect#147]
On the menu that appears in the widget, after selecting a device.

Should be fixed to **Keyboard**

**Comment by Bajoja** [comment]
[Same for](https://github.com/Bajoja/indicator-kdeconnect/issues/146#issuecomment-443525989)

**Comment by danilo-bc** [comment]
I think I've corrected the appropriate line/file. Since I don't know the full structure of this project, I can't simply search all source code files for "keybord" and correct it.

**Comment by Bajoja** [comment]
No problem, thank you by the way
