### ISSUE TITLE
[Feature Request] .rpm package

### ISSUE THREAD

**Issue by lauren-elise-thomas** [Bajoja/indicator-kdeconnect#15]
self explanatory

**Comment by Bajoja** [comment]
Well, i can provide rpm package because i use Fedora, but i expecting is more easily someone provide a repo for Fedora and OpenSuse.

**Comment by Bajoja** [comment]
You can install it from the repo on the readme file or download .rpm package from the follow address http://download.opensuse.org/repositories/home:/Bajoja/Fedora_25/x86_64/

**Comment by lauren-elise-thomas** [comment]
thanks!
