### ISSUE TITLE
[Bug?] SMS notifications, 5x notifications each time

### ISSUE THREAD

**Issue by BloodyIron** [Bajoja/indicator-kdeconnect#150]
Just started using KDE connect on XFCE4 with my LG v20, and SMS messages coming in, I get 5x notifications each time, it's really annoying.

* kdeconnect 1.3.1-1
* indicator-kdeconnect 0.9.4-1

**Comment by Bajoja** [comment]
Hi, we don't manage notification on indicator-kdeconnect, so i recommend you to check this 2 issue. #119 #113

**Comment by BloodyIron** [comment]
You're misunderstanding, I'm talking about the notifications sent to my desktop are duplicate. So yes that is being served by indicator-KDEconnect.

**Comment by andyholmes** [comment]
indicator-kdeconnect is just a tray icon to run DBus functions from a menu.

The notifications are sent by `kdeconnectd` directly and don't pass through the indicator, nor does the indicator have any way to prevent them from being sent.

The first thing you should try is force stopping the Android app and clearing the cache. If that doesn't work, you'll have to file an upstream bug report.

**Comment by Bajoja** [comment]
@BloodyIron Check the tips provided by @andyholmes

**Comment by PocketSam** [comment]
I've had a same problem, every time I've recieved SMS I saw 13 notifications. Clearing all app info on Android and re-registering with a KDE Connect solved the problem. Also I'm using MIUI, so I've had to allow all application background activity and autorun after application reset.
