### ISSUE TITLE
Can not remove icon on the top bar

### ISSUE THREAD

**Issue by cdnhermit** [Bajoja/indicator-kdeconnect#153]
I am sorry if I am addressing this BUG at the wrong place.
Configure KDE Connect Indicator icon located on the top bar can not be remove. I just installed Ubuntu 18.04.1 and there was this unknowned icone so I clicked on it and i can not make it disapear. I do not have any of android or pocket phone.

**Comment by smac89** [comment]
Open task manager and look for kdeconnect. Kill any process with such name
