### ISSUE TITLE
Apt update: no Release file

### ISSUE THREAD

**Issue by stephanvierkant** [Bajoja/indicator-kdeconnect#16]
After adding the PPA, I get this error message during `sudo apt update`:

> E: The repository 'http://ppa.launchpad.net/varlesh-l/indicator-kdeconnect/ubuntu yakkety Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

How can I solve this problem?

**Comment by varlesh** [comment]
```
sudo add-apt-repository 'deb http://ppa.launchpad.net/varlesh-l/indicator-kdeconnect/ubuntu xenial main'
sudo apt update
sudo apt install indicator-kdeconnect
```

**Comment by varlesh** [comment]
PPA For Xenial only, but will be worked with Ubuntu 16.10

**Comment by varlesh** [comment]
Also delete errored source list:
`sudo rm /etc/apt/sources.list.d/varlesh-l-ubuntu-indicator-kdeconnect-yakkety.list.save`

**Comment by Bajoja** [comment]
@stephanvierkant follow varlesh tips, because these PPA is for Ubuntu 16.04.

**Comment by Ads20000** [comment]
Is there a reason why you can't release this for Ubuntu 16.10 too? :)

**Comment by varlesh** [comment]
program worked - it's main! 16.10 support only 9 months and i'm don't won support nonLTS-release

**Comment by varlesh** [comment]
Sorry, i'm not have time for maintaining non-LTS release... if you want will be maintainer PPA for all releases - welcome!

**Comment by Bajoja** [comment]
@Ads20000, it's how varlesh say, he don't have time to maintain a non LTS system and can't do that because i don't use Ubuntu, but if you want to maintain it -welcome!
