### ISSUE TITLE
Shared library is mispackaged

### ISSUE THREAD

**Issue by rgson** [Bajoja/indicator-kdeconnect#164]
The shared library (`libindicator-kdeconnect.so`) is mispackaged in a way that breaks the Debian policy and best practices, but more importantly, fails to update the dynamic library loader's cache when installed.

Best practice would be to package the shared library in a separate package and to include the library version in the filename of the .so file. If packaged according to convention, I believe `dh_makeshlibs` would take care of the dynamic library loader's cache automatically.

This is related to three Lintian warnings/errors:
```
W: indicator-kdeconnect: package-name-doesnt-match-sonames libindicator-kdeconnect
W: indicator-kdeconnect: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libindicator-kdeconnect.so libindicator-kdeconnect.so
E: indicator-kdeconnect: package-must-activate-ldconfig-trigger usr/lib/x86_64-linux-gnu/libindicator-kdeconnect.so
```
See:
- [Lintian Tag: package-name-doesnt-match-sonames](https://lintian.debian.org/tags/package-name-doesnt-match-sonames.html)
- [Lintian Tag: shlib-without-versioned-soname](https://lintian.debian.org/tags/shlib-without-versioned-soname.html)
- [Lintian Tag: package-must-activate-ldconfig-trigger](https://lintian.debian.org/tags/package-must-activate-ldconfig-trigger.html)

**Comment by Bajoja** [comment]
Hi @rgson, thank you for your contribution, actually i have few time to work on this, and any help with this will be welcome.
Same for #162 #161 and #163

**Comment by rgson** [comment]
I completely understand. These aren't critical issues either, I just figured I ought to report it somewhere when I noticed. I'll send PRs if I find the time to fix them myself.
