### ISSUE TITLE
Two commits missing

### ISSUE THREAD

**Issue by KAMiKAZOW** [Bajoja/indicator-kdeconnect#18]
KDE Connect developer applied two unanswered pull requests from the original branch to his fork – the one by aleixpol and one by nicklan: https://github.com/albertvaka/indicator-kdeconnect/commits/master

**Comment by Bajoja** [comment]
Before starting this fork, I carefully studied the fork of both albertvaka and vikoadi, and I came to the conclusion that the changes I had in mind did not mention these commits, this is why i clone the original and not the albertvaka.
