### ISSUE TITLE
Fedora install instructions are slightly incorrect

### ISSUE THREAD

**Issue by pbzeppelin** [Bajoja/indicator-kdeconnect#22]
>sudo dnf config-manager --add-repo http://download.opensuse.org/repositories/home:/Bajoja/Fedora_25/home:Bajoja.repo
>sudo dnf update
>sudo dnf install kdeconnectd indicator-kdeconnect -y

Should not have the `dnf update` command - in DNF that does a full system upgrade (it's the DNF equivalent of `apt-get upgrade`). DNF updates its package lists automagically after a set amount of time (I forget the default) when a command is given rather than manually like apt-get. After the repo is added, DNF will download the data and look for the packages when the install command is given.

**Comment by Bajoja** [comment]
@pbzeppelin thanks for the advice, i didn't know that.
