### ISSUE TITLE
Google Pixel - Device Not Trusted

### ISSUE THREAD

**Issue by bdodroid** [Bajoja/indicator-kdeconnect#23]
Im on a stock Google Pixel on Ubuntu 16.10 and after installing and configuring I'm getting "Device reachable but not trusted" on the drop down. 
I can ping to and from phone and send files from phone to computer but I get no extra functionality from the computer to the phone. No browsing, find phone, nothing. 

Any ideas?

**Comment by Bajoja** [comment]
Ok, you aren't the first people saying Android Nougat not working with these feature, the only thing i can tell you is, check if the these plugins are enable on the android app, case otherwise KDEConnect has not yet been update to work with it.

**Comment by bdodroid** [comment]
Ah, ok so its Nougat that's most likely the issue. Thanks for the quick reply

**Comment by d0od88** [comment]
I experience this with devices with Marshmallow as well as Nougat.

**Comment by Bajoja** [comment]
@bdodroid the problem seems to be the version of KDEConnect, reed this article and see how to solved, http://www.omgubuntu.co.uk/2017/01/kde-connect-indicator-ubuntu
