### ISSUE TITLE
Allow user to set destination folder before sending file from PC to phone

### ISSUE THREAD

**Issue by raztd** [Bajoja/indicator-kdeconnect#24]
When I tried to send a file from pc to phone, the transfer started automatically and the file was sent to the Downloads folder, on the internal memory. I would like to be able to choose where a file should go, before the transfer starts.

PS: I'm using Android 6.0

**Comment by Bajoja** [comment]
@raztd on the KDEConnect app for android you can choose were files will be save by default, but at the transfer time it's not possible do that.
