### ISSUE TITLE
AUR pulls in too many dependencies

### ISSUE THREAD

**Issue by rodneyrod** [Bajoja/indicator-kdeconnect#27]
Trying to compile from the indicator-kdeconnect-git but the kde-connect dependency pulls in just about every KDE package it can, and I would have thought programs such as kwallet weren't needed when using this.

**Comment by Bajoja** [comment]
@rodneyrod to compile the indicator you don't need Kdeconnect, you need it only to execute the indicator. In some DE kdeconnect install only the necessary but in arch case I don't know but I not supposed to install things like wallet.

**Comment by rodneyrod** [comment]
Well would it be possible to put together a kde-connect dependency that will only pull in the minimum packages needed and put that in an AUR?

**Comment by Bajoja** [comment]
@rodneyrod yes i think it's possible, but contact the AUR package maintainer, maybe he can do this, i don't understand nothing about AUR.
https://aur.archlinux.org/packages/indicator-kdeconnect-git/
