### ISSUE TITLE
Error: Encryption information not found

### ISSUE THREAD

**Issue by nazarimilad** [Bajoja/indicator-kdeconnect#29]
When I click on the name of my smartphone device, on the kde connect icon. I get this error message:
 
![image](https://cloud.githubusercontent.com/assets/23218676/21939392/eb6b3f92-d9bf-11e6-9b71-7c318d51823d.png)
 
Also the list of plugins seems empty for me: 

![image](https://cloud.githubusercontent.com/assets/23218676/21939439/1a49acd6-d9c0-11e6-9135-2558091dbf9d.png)

I'm using Ubuntu 16.10.

**Comment by Bajoja** [comment]
Check the version of both kdeconnect and kdeconnect android, if they are updated check if the plugins on the android app are enabled.

**Comment by nazarimilad** [comment]
I removed it and installed it again. I think I used the wrong PPA the first time. It works now. Thanks!

**Comment by moobsen** [comment]
I get the same error but purging kdeconnect and indicator-kdeconnect did not help. Any suggestions? 
I am running Xubuntu 16.04.3 LTS
