### ISSUE TITLE
segmentation fault on Debian stretch

### ISSUE THREAD

**Issue by fulgorit** [Bajoja/indicator-kdeconnect#31]
I have done with cmake . and make but :

./indicator-kdeconnect 

(indicator-kdeconnect:24710): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(indicator-kdeconnect:24710): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(indicator-kdeconnect:24710): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault

**Comment by varlesh** [comment]
try deb-package for Xenial:
https://launchpad.net/~varlesh-l/+archive/ubuntu/indicator-kdeconnect/+packages
I know this not debian, but maybe working

**Comment by Bajoja** [comment]
When kdeconnect dbus service is not present, that means you don't install kdeconnect or kdeconnect is not running, check if you install it.
