### ISSUE TITLE
Add French language

### ISSUE THREAD

**Issue by Rodney78** [Bajoja/indicator-kdeconnect#35]
Hello,

Can you add French as translatable language in Weblate? I'd like to translate your project in my mother tongue as I really enjoy using it!

**Comment by detobel36** [comment]
I begin to make it and open a pull request soon :smile:

**Comment by detobel36** [comment]
@Rodney78 in French:           
Voilà, j'ai normalement traduit le fichier :smile:    Je suis par contre très mauvais en orthographe :confused:           
N'hésitez pas à corriger :wink:

**Comment by Rodney78** [comment]
Thank you @detobel36 I fixed some strings but the great majority was OK
