### ISSUE TITLE
Control phone music

### ISSUE THREAD

**Issue by detobel36** [Bajoja/indicator-kdeconnect#37]
Could you add a features: _control phone music_

------------------------------------

It could be cool to control phone music:
- play
- pause
- volume
- next
- previous

(I could may be help you if you tell me what is must to do :smile: :confused: )

---------------------
Label: `enhancement`

**Comment by Bajoja** [comment]
@detobel36 It would be interesting but the kdeconnect API still does not allow to do this, since it is necessary to have a plugin in the android kdeconnect app that allowed to do this.
