### ISSUE TITLE
How to install it on debian (sid)?

### ISSUE THREAD

**Issue by hista** [Bajoja/indicator-kdeconnect#39]
All is in the title :)

**Comment by Bajoja** [comment]
¯\_(ツ)_/¯

**Comment by Bajoja** [comment]
Well i don't use debian based systems, but download the last release from https://github.com/Bajoja/indicator-kdeconnect/releases and install it with "sudo dpkg -i 'indicator' " replace ''indicator' to the x86 or amd64 package you download.
But before this make sure you install kdeconnect, i don't know if kdeconnect is on debian repo, but try "sudo apt install kdeconnect" and then run "kdeconnect-cli -v" on terminal to ensure you have version 1.0 or up. If is not on repo you have to search the kdeconnect install package on the internet.

**Comment by hista** [comment]
Thanks for your answer.
My kdeconnect-cli is version 1.0
I tried what you suggested, but there is a dependency issue:

> sudo dpkg -i indicator-kdeconnect_0.6_amd64.deb 
Selecting previously unselected package indicator-kdeconnect.
(Reading database ... 394945 files and directories currently installed.)
Preparing to unpack indicator-kdeconnect_0.6_amd64.deb ...
Unpacking indicator-kdeconnect (0.6ubuntu16.04.1) ...
dpkg: dependency problems prevent configuration of indicator-kdeconnect:
 indicator-kdeconnect depends on ubuntu-mono; however:
  Package ubuntu-mono is not installed.

> dpkg: error processing package indicator-kdeconnect (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for gnome-menus (3.13.3-8) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 indicator-kdeconnect

**Comment by Bajoja** [comment]
@hista on the terminal execute "sudo apt install ubuntu-mono"

**Comment by hista** [comment]
The problem is it's obviously an ubuntu package, which isn't available on debian:
> Reading state information... Done
Package ubuntu-mono is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'ubuntu-mono' has no installation candidate


And apt-cache search ubuntu-mono returns nothing.

And 
> apt-cache policy ubuntu-mono
ubuntu-mono:
  Installed: (none)
  Candidate: (none)
  Version table:

**Comment by fitojb** [comment]
The package “ubuntu-mono” is contained in the package “ubuntu-themes”.

**Comment by hista** [comment]
It's the same:
> apt-cache policy ubuntu-themes
N: Unable to locate package ubuntu-themes

> apt-get install ubuntu-themes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ubuntu-themes

**Comment by fitojb** [comment]
Well, that’s obvious if you’re in Sid ;-). Just download the package from Launchpad.net and install it with dpkg or GDebi.

In https://launchpad.net/ubuntu/zesty/+source/ubuntu-themes, scroll to the section “Binary packages” and pick the package that matches your architecture (i386, amd64, etc.)

**Comment by Bajoja** [comment]
Or what @fitojb say don't work install it from the source https://github.com/Bajoja/indicator-kdeconnect/blob/master/INSTALL, follow the Ubuntu instructions

**Comment by H2L29** [comment]
Depends: ${misc:Depends}, ${shlibs:Depends}, kdeconnect, **ubuntu-mono**

make depends to a distro related not really necessary package is a nonsense

**Comment by Bajoja** [comment]
For the next releases i will drop this depends
