### ISSUE TITLE
compilation failed because of Sms.vala

### ISSUE THREAD

**Issue by the-livingstone** [Bajoja/indicator-kdeconnect#40]
$ make
[  7%] Generating src/Constants.c;src/main.c;src/Device.c;src/KDEConnectManager.c;src/DeviceIndicator.c;src/FirstTimeWizard.c;src/StartupManager.c;src/Sms.c
warning: --save-temps has no effect when -C or --ccode is set
/home/livingstone/ssd/indicator-kdeconnect-master/src/Sms.vala:52.37-52.58: error: 1 missing arguments for `void Gtk.EntryBuffer.new (uint8[] initial_chars)'
        	this.phone_number_buffer = new Gtk.EntryBuffer ();
        	                           ^^^^^^^^^^^^^^^^^^^^^^
/home/livingstone/ssd/indicator-kdeconnect-master/src/Sms.vala:65.10-65.47: error: The name `set_top_margin' does not exist in the context of `Gtk.TextView'
        	this.message_body_entry.set_top_margin (6);
        	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/livingstone/ssd/indicator-kdeconnect-master/src/Sms.vala:66.10-66.50: error: The name `set_bottom_margin' does not exist in the context of `Gtk.TextView'
        	this.message_body_entry.set_bottom_margin (6);
        	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 3 error(s), 1 warning(s)

**Comment by Bajoja** [comment]
![captura de ecra de 2017-02-08 21-39-08](https://cloud.githubusercontent.com/assets/10621831/22758861/494c8976-ee48-11e6-8924-b75e67b71fce.png)
![captura de ecra de 2017-02-08 21-39-10](https://cloud.githubusercontent.com/assets/10621831/22758870/4f58b1d2-ee48-11e6-8659-4866c21c3000.png)

**Comment by Bajoja** [comment]
@the-livingstone need more information like vala version because every ting is working here.

**Comment by MrMarukesu** [comment]
@Bajoja This error occurs in vala 0.22.1 used in Travis
