### ISSUE TITLE
don't show notifications on Ubuntu

### ISSUE THREAD

**Issue by BennyThink** [Bajoja/indicator-kdeconnect#44]
Hi there,
I'm using kde connect on Ubuntu 16.04.
However, it did not show any notifications on my Ubuntu.
If I restart kde connect, and send ping from my phone, Ubuntu would only show it only **once**.
Kde app has already gain access to read notifications, all the plugins has enabled.
However, Ubuntu's notifications could be sent to my phone.

My phone: HTC one m8
OS: Ubuntu 16.04 LTS

Thank you!

**Comment by Bajoja** [comment]
@BennyThink  see #32.
I would say again, indicator don't manage notification. 
Report this kind of bug to KDEConnect, not indicator-kdeconnect
