### ISSUE TITLE
[Request] Flatpack Repository

### ISSUE THREAD

**Issue by Eeveel** [Bajoja/indicator-kdeconnect#45]
Hi,
Is it possible to have a Flatpack Repository, that can allow to easily install and update indicator-kdeconnect in all distributions for Linux environment user?
Thanks for your hard work!

**Comment by Bajoja** [comment]
Have a Flatpack Repository will be nice, if someone want's to criete it would be great.
The for a snap package.
At this time i can't because i don't understand nothing about Flatpack.

**Comment by Bajoja** [comment]
I move this to #49
