### ISSUE TITLE
SMS - Provide search contacts feature

### ISSUE THREAD

**Issue by Bajoja** [Bajoja/indicator-kdeconnect#48]
After many requests I have tried to find a way to make available the search of contacts in sending msg, I believe the best applications to do this will be the gnome contacts that has integration with the google services.
But I can not work with the gnome contacts API in Dbus, if someone who is already accustomed to gnome contacts wants to help, I would be grateful.

Here is the bug of gnome contacts API in Dbus:
![peek_2017-03-18_19-08](https://cloud.githubusercontent.com/assets/10621831/24075528/277d5c72-0c15-11e7-8820-7c6ea7659b70.gif)

**Comment by OzymandiasTheGreat** [comment]
Unfortunately I can't help as I do not know Vala, but while waiting for this feature to be implemented
I wrote a [simple script](https://github.com/OzymandiasTheGreat/send-sms) as a replacement for send sms functionality that supports Google Contacts sync and autocomplete. Figured I'd link it here for anyone who's looking for temporary solution.
Also just a question, must you depend on gnome contacts? Implementing direct sync is pretty simple, just a handful of http requests and json parsing.

**Comment by Bajoja** [comment]
@OzymandiasTheGreat, the use of gnome contacts it's because it have a DBus API and most DE's have it like gnome, but Android contacts it's almost on google, so use only gnome can be a great solution.
I will look your code and check if there a way to linked or ported to this app, even if it is temporary.

**Comment by OzymandiasTheGreat** [comment]
@Bajoja Do let me know if there's anything I can do to help, like any changes I need to make to ease integration.

**Comment by Bajoja** [comment]
Ok, i test it and i like your ideia, so my ideia is make the interface more like the actual one and make it acept args (the device id), then from the indicator call the python executable for the sms send.

I will create a dev branch of indicator-kdeconnect and you will upload the code the code to the folder /src/ with the name Sms.py.

I will port the interface just like is it on the indicator and you can make it accept the arg i mention above.

And indicator-kdeconnect will call it like this "Sms.py -d the_device_id" 

And of course only if you accept do this, let me know if you agree.

**Comment by OzymandiasTheGreat** [comment]
@Bajoja Of course I agree. Never worked with headerbars, but this shouldn't be hard. It's getting late here, so I'll probably have working version tomorrow.

**Comment by Bajoja** [comment]
@OzymandiasTheGreat, clone and make a pull request with the code on this branch https://github.com/Bajoja/indicator-kdeconnect/tree/send-sms-dev 

Don't worry I'm working on the header bar right now.

**Comment by Bajoja** [comment]
@OzymandiasTheGreat, as the old SMS send, can you make the send button non clickable until user input some phone number and message text?

**Comment by OzymandiasTheGreat** [comment]
@Bajoja it is done. I also propose some changes for cleaner integration in the comment on the pull request.

**Comment by OzymandiasTheGreat** [comment]
@Bajoja could you reply to [this comment](https://github.com/Bajoja/indicator-kdeconnect/pull/55#issue-222681470)? I really think changing data location and authorization page is necessary.

**Comment by Bajoja** [comment]
I will mark this as solved because we have integration with Google Contacts
