### ISSUE TITLE
cannot connect to KDE Connect DBus service

### ISSUE THREAD

**Issue by Jab2870** [Bajoja/indicator-kdeconnect#50]
I have installed indicator-kdeconnect and tried to run it but I get an alert box that says 
`cannot connect to KDE Connect DBus service`

I am using i3 as my window manager.

Can anybody help?

**Comment by Bajoja** [comment]
That means you don't have kdeconnect installed or it not running.

**Comment by Jab2870** [comment]
Thanks, i have it kdeconnect installed, how would i start it?

**Comment by hotice** [comment]
You may have an older version of KDE Connect. I encountered this issue while testing KDE Connect Indicator in Linux Mint 18 without adding the PPA. So I had KDE Connect 0.8, instead of 1.0.3.

**Comment by Jab2870** [comment]
Hi, thanks all,

In case anybody ever comes accross this I solved it by running the kde connect deamon first.  In the case of i3, I added the following lines to my i3 config
```
exec --no-startup-id /usr/lib/kdeconnectd
exec --no-startup-id indicator-kdeconnect
```

It might be a good idea to add this to the readme

**Comment by Bajoja** [comment]
@Jab2870 maybe this only happen on i3, because on other's DE the indicator-kdeconnect and kdeconnect is added to start up applications

**Comment by aiot-dev** [comment]
I have this problem on Gentoo Gnome shell 3.22.2, too.

**Comment by aiot-dev** [comment]
@Jab2870 error: exec: --: invalid option

**Comment by Bajoja** [comment]
@aiot-dev  on Gnome Shell use the tool 'gnome-tweek-tool' to add them to start up applications.

**Comment by fademyke** [comment]
@Bajoja 'gnome-tweak-tool' only shows KDE Connect Indicator as a startup option, for me.

**Comment by Bajoja** [comment]
@fademyke but KDEConnect already autostart with your system?
