### ISSUE TITLE
Nemo extension: Error while getting reachable devices

### ISSUE THREAD

**Issue by hotice** [Bajoja/indicator-kdeconnect#51]
Tested in Ubuntu 17.04 and Linux Mint 18.1, using the latest Nemo version (3.2.2) and indicator-kdeconnect 0.7.0, there's no Nemo context menu for KDE Connect. This is displayed when starting Nemo from a terminal:

```
** (nemo:15472): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed

** (nemo:15472): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed

(nemo:15472): Gtk-WARNING **: Allocating size to NemoWindowPane 0x56542afae430 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:15472): Gtk-WARNING **: Allocating size to NemoWindowPane 0x56542b1137a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/kdeconnect-send-nemo.py", line 75, in get_file_items
    raise Exception("Error while getting reachable devices")
Exception: Error while getting reachable devices
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/kdeconnect-send-nemo.py", line 75, in get_file_items
    raise Exception("Error while getting reachable devices")
Exception: Error while getting reachable devices
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/kdeconnect-send-nemo.py", line 75, in get_file_items
    raise Exception("Error while getting reachable devices")
Exception: Error while getting reachable devices

** (nemo:15472): WARNING **: connect() failed
```

**Comment by Bajoja** [comment]
I will check this soon

**Comment by Bajoja** [comment]
@hotice build the new version with this bug solved to the ppa

**Comment by szekeres2016** [comment]
@Bajoja checked it, it does work now, but it still only shows a single connected device like how the nautilus extension used to before you fixed that.

**Comment by Bajoja** [comment]
The code to get devices are the same, i don't know why.
![nemo](https://cloud.githubusercontent.com/assets/10621831/24883021/10ac1758-1e3b-11e7-801f-2cc3921c7ea0.png)
![nautilus](https://cloud.githubusercontent.com/assets/10621831/24883026/14b54e46-1e3b-11e7-8de1-65b42983756a.png)

**Comment by Bajoja** [comment]
@szekeres2016 for now i recomend use kdeconnect-send aplication, you can integrate it with your file manager with this [script](https://github.com/Bajoja/indicator-kdeconnect/tree/master/scripts/kdeconnect-send) load it on nemo plugins.

![screenshot at 2017-04-18 01-32-22](https://cloud.githubusercontent.com/assets/10621831/25109771/12188c4c-23d7-11e7-8298-2f4096e7ba6b.png)
