### ISSUE TITLE
HIDPI Support for Indicator Icons

### ISSUE THREAD

**Issue by jens-t** [Bajoja/indicator-kdeconnect#53]
Nice work, thanks!

I need some help fixing the indicator icons (see screenshot).
Already copied the icons from the repository to multiple icon folders on my machine, but the indicator always uses the blurred icons. i cant find the file where the icon path is declared ...

I use Ubuntu Gnome 16.04 with Arc & Papirus Icon Theme.

Any Help would be very appreciated! Thanks!

![screen](https://cloud.githubusercontent.com/assets/9143480/25073128/f60db416-22df-11e7-8598-59613b989aa8.png)

**Comment by Bajoja** [comment]
Hi @jens-t, on Ubuntu icons is saved on /usr/share/icons/ubuntu-mono-dark/ and /usr/share/icons/ubuntu-mono-light/, but the icons that you have on the indicator come from Papirus Icon Theme, so if you wanna replace that icon you have to find where Papirus save it, at this point i can't help you, the person that design the icons for this project is no more available, maybe other one here can help you.

**Comment by jens-t** [comment]
Hey @Bajoja, thanks for the info. Yeah, already added the icons to the papirus theme. I found out, that this is not the the problem, any icon from any icon theme is blurred. (see the screenshots) Perhaps it is the way the icon is embedded or declared in the indicator script? (Do you know where this is done?) Maybe that's only a gnome hdpi problem ... i investigate further ... 
![hicolor](https://cloud.githubusercontent.com/assets/9143480/25092329/7a569cb2-238d-11e7-91fa-53f37854fdb7.png)
![ubuntu-mono-dark](https://cloud.githubusercontent.com/assets/9143480/25092330/7a59f9ca-238d-11e7-908d-d7e07c69a1d6.png)

**Comment by Bajoja** [comment]
The icon is just called in his natural form on the code, it not suffer any alteration, how you say maybe is just a hdpi problem or something is resizing the icons, do you use the gnome extension "indicator app for gnome support"? that extension rezise icons.

**Comment by jens-t** [comment]
Yeah, i use Topicons Plus. Which resizes Icons, but i already deactivated the extension to test this. And the Icon is still blurry, compared to the other icons. Not that blurry as with Topicons enabled, but still blurry. The Topicons Resize-Problem is easily fixed, by setting a size which exists as icon folder, e.g. 16, 22 or 24.

I noticed that the svg's have no viewport attribute declared. I added the viewport, but that didn't help either.

**Comment by Bajoja** [comment]
Yah, looks better now, but i can't do nothing for you, how i say icons is not my area, maybe someone else can help you.

**Comment by Bajoja** [comment]
@jens-t any news about this?

**Comment by Bajoja** [comment]
Like @varlesh say probably is a libappindicator bug so i will close this.
