### ISSUE TITLE
Failed to execute child process “/usr/share/indicator-kdeconnect/Sms.py” (Permission denied)

### ISSUE THREAD

**Issue by hotice** [Bajoja/indicator-kdeconnect#59]
I was in the process of updating the new KDEConnect Indicator PPA when I encountered a bug. When selecting "Send SMS" from the indicator, this is displayed on the console (and the send SMS dialog box is not displayed):
```
** Message: DeviceIndicator.vala:132: Failed to execute child process “** Message: DeviceIndicator.vala:132: Failed to execute child process “/usr/share/indicator-kdeconnect/Sms.py” (Permission denied)” (Permission denied)
```
This is fixed after changing the /usr/share/indicator-kdeconnect/Sms.py permissions but I thought I'd let you know anyway. This is using indicator-kdeconnect 0.8.0.

**Comment by Bajoja** [comment]
I need the build log, because there is a update permission on cmake file the is executed on installation

**Comment by hotice** [comment]
Sure, here's the build log: https://launchpadlibrarian.net/316804903/buildlog_ubuntu-zesty-amd64.indicator-kdeconnect_0.8.0-1~webupd8~zesty_BUILDING.txt.gz

And the deb if you want to test it: https://launchpad.net/~nilarimogard/+archive/ubuntu/test/+files/indicator-kdeconnect_0.8.0-1~webupd8~zesty_amd64.deb

**Comment by Bajoja** [comment]
Here is the problem, i will patch a solution for file not found.

![captura de ecra de 2017-04-24 13-39-26](https://cloud.githubusercontent.com/assets/10621831/25337434/c540cb24-28f3-11e7-8b9d-588927399381.png)

**Comment by hotice** [comment]
Yeah... the relative path needs to be used. Until it's fixed I tweaked the PPA package to work around this issue, so I can update the PPA.
