### ISSUE TITLE
Extensions create on home folder buildd

### ISSUE THREAD

**Issue by varlesh** [Bajoja/indicator-kdeconnect#6]
CMake create extensions on `/home/buildd/.local/share/`
log build and package:
https://launchpad.net/~varlesh-l/+archive/ubuntu/test/+build/11239556

**Comment by varlesh** [comment]
Maybe better use system folders?

**Comment by Bajoja** [comment]
Thanks for report, i already change it to system folders.

**Comment by varlesh** [comment]
FIne. But how this worked? It's option for context menu?
I'm install fresh version, but Nautilus not seen extension

**Comment by Bajoja** [comment]
Yes, it's a context menu, to work you have to have the python extension for your file manager, in your case do '''sudo apt install python-nautilus''' to install it, and then '''nautilus -q''' to restart nautilus.

**Comment by varlesh** [comment]
it's for nautilus only, but this will be not working for caja and nemo... hm. Maybe add recommends depend python-caja, python-nautilus
And what package available for nemo?

**Comment by varlesh** [comment]
I found package name nemo-python, but not available on ubuntu repos for xenial :(
I'm add as **Suggests packages**:
```
...
Architecture: any
Depends: ${misc:Depends}, ${shlibs:Depends}, kdeconnect
Suggests: python-nautilus, python-caja, python-nemo
Description: Indicator for KDE Connect
```

**Comment by Bajoja** [comment]
For nemo i think it's python-nemo, Caja on Cinamon have python extensions for Caja installed by default, other distributions without cinnamon I can not find python-caja, or any other reference to install the python caja

**Comment by varlesh** [comment]
i'm build package for ubuntu 16.04 and available only `python-nautilus`, `python-caja`.
`python-nemo` not available on off repos, but exist on webupd8 PPA:
https://launchpad.net/~webupd8team/+archive/ubuntu/nemo
So, it's not our problem :) because it's optional and added as Suggests packages

**Comment by Bajoja** [comment]
Exactly, it's not our problem because it's optional

**Comment by Bajoja** [comment]
@varlesh build the source on the ppa, i will need the deb package for 0.6 release.

**Comment by varlesh** [comment]
@Bajoja updated:
https://launchpad.net/~varlesh-l/+archive/ubuntu/indicator-kdeconnect/+packages

https://launchpad.net/~varlesh-l/+archive/ubuntu/indicator-kdeconnect/+files/indicator-kdeconnect_0.6ubuntu16.04.1_amd64.deb
https://launchpad.net/~varlesh-l/+archive/ubuntu/indicator-kdeconnect/+files/indicator-kdeconnect_0.6ubuntu16.04.1_i386.deb

**Comment by Bajoja** [comment]
@varlesh Thank's
