### ISSUE TITLE
SMS contact automcomplete issue

### ISSUE THREAD

**Issue by hotice** [Bajoja/indicator-kdeconnect#60]
After I try to authorize KDEConnect Indicator (0.8.0) with my Google account, this error occurs:
```
** Message: DeviceIndicator.vala:288: Status found on file - HTC One M8 : 21f499737fc8fb85

Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 294, in sync
    self.contacts = google_contacts.get_contacts()
  File "/usr/share/indicator-kdeconnect/Sms.py", line 140, in get_contacts
    self.get_consent()
  File "/usr/share/indicator-kdeconnect/Sms.py", line 92, in get_consent
    self.serve_redirect()
  File "/usr/share/indicator-kdeconnect/Sms.py", line 77, in serve_redirect
    httpd = HTTPServer((ip, int(port)), RequestHandler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[25080:25122:0424/140847.656864:ERROR:nss_util.cc(808)] After loading Root Certs, loaded==false: NSS error code: -8018
Created new window in existing browser session.
```

This occurs because the address is already in use. Is there some configuration option to change this?

**Comment by Bajoja** [comment]
That means probably you have another process listening on that port.
Try to locate first, run 'ps -fA | grep python' to check if is another python process.
@OzymandiasTheGreat any suggestion?

**Comment by hotice** [comment]
Yes but I think port 8000 is pretty common so probably more users will run into this issue.... Also, after authenticating, the autocomplete doesn't work for me and there's no error message to indicate why.

**Comment by Bajoja** [comment]
@hotice don't try it with numbers try with characters.

**Comment by hotice** [comment]
I tried both numbers and characters, but nothing is autocompleted. I even tried it by typing the complete name of a contact and trying to send an SMS, with no result.

**Comment by Bajoja** [comment]
The folder "/home/{USERNAME}/.local/share/indicator-kdeconnect/sms" is empty?

**Comment by hotice** [comment]
There's a token.json and contacts.json file (it only contains "[]" without any actual contacts). How long should this take?

**Comment by Bajoja** [comment]
The file is update every time you press the sync button

**Comment by OzymandiasTheGreat** [comment]
Sorry for being late.
@hotice Tried to replicate this, but it seems the two issues aren't related. Syncing should work as soon as the port is freed up or changed. Is the token.json file also empty? Does syncing output anything else to the terminal? Also could you try deleting token.json and try syncing again? This would at least confirm that the issue is caused by malformed token.
@Bajoja Totally my bad, I do think we should change the port to something less likely to be used. That's '8000' on line 67.

**Comment by Bajoja** [comment]
@OzymandiasTheGreat any suggestion of a port that's rarely used?

**Comment by OzymandiasTheGreat** [comment]
@Bajoja how about 8013? A quick google search doesn't turn up anything that might be using it.

**Comment by szekeres2016** [comment]
I'm not sure if the issue I'm experiencing with this new (btw really cool) feature, but I noticed that accented letters like é, á and others of the sort will result in 0 matches upon search. Regular letter searches work well however. These letters are quite common in my address book so can't exactly use workarounds for search. I really don't want to hijack this thread, so I will post a new ticket if this has nothing to do with this of course.

**Comment by Bajoja** [comment]
@OzymandiasTheGreat  8013 sounds nice.

Mrs @szekeres2016 post and interesting question, i test it and accented letters is not detected.

**Comment by OzymandiasTheGreat** [comment]
@Bajoja , @szekeres2016 Confirmed, seems to be a bug in the way GTK+ casefolds unicode characters.
Got a fix in my fork, should I send a pull request?

**Comment by Bajoja** [comment]
@OzymandiasTheGreat of course, waiting for the pull request, and change the port to 8013

**Comment by Bajoja** [comment]
@szekeres2016 can you test the last commit and see if everything is working for you accented letters and the Nemo showing only 1 device?

**Comment by szekeres2016** [comment]
@Bajoja I've just compiled it, and it works!

**Comment by Bajoja** [comment]
@szekeres2016 thanks, i will release 0.8.1 to fix this issues.
