### ISSUE TITLE
QSystemTrayIcon::setVisible: No Icon set

### ISSUE THREAD

**Issue by thymbahutymba** [Bajoja/indicator-kdeconnect#63]
Hi Guys, i have one problem with kdeconnect into gnome/budgie desktop. When i try to launch kdeconnect indicator i have one error:
`QSystemTrayIcon::setVisible: No Icon set`
How i can resolve this?

**Comment by moeenio** [comment]
Did you resolve it? Please share your solution.

**Comment by thymbahutymba** [comment]
No, I did not resolve it. Sorry

**Comment by moeenio** [comment]
Then, the issue should stay open
