### ISSUE TITLE
Browse external SD card?

### ISSUE THREAD

**Issue by willsALMANJ** [Bajoja/indicator-kdeconnect#66]
Is it possible to browse the contents of an external SD card? With "Browse device", I can see and modify the contents of the main SD card, but I can't see the external one. In the KDE app, I chose a location on the external SD card for the "Destination directory" in the "Share and receive settings" section and I am able to use the indicator's "Send file(s)" feature to send files from my laptop to the external SD card. So the app can access the external SD card, but I haven't found a way to browse to it. I know Android is weird about what you can and can't do with the external SD card....

**Comment by Bajoja** [comment]
It's supposed to both appear when you click browse device, one folder to sdcard another one to file system.

**Comment by OzymandiasTheGreat** [comment]
That's a bug in KDE Connect proper. KDE Connect can't list contents of external SD card but if you manually enter path to a folder on an external SD card it works fine.
For example, assuming external SD card is mounted on `~/.config/kdeconnect/device_id/kdeconnect_sftp/device_id/mnt/extSdCard`, this folder appears empty, but if you go to `~/.config/kdeconnect/device_id/kdeconnect_sftp/device_id/mnt/extSdCard/Music` your files are listed normally.
You can find more info on this [bug](https://bugs.kde.org/show_bug.cgi?id=336043) on KDE bug tracker.

**Comment by willsALMANJ** [comment]
Hmm, I only see the folder for the internal sdcard, not the external one. After `.../kdeconnect_sftp/device_id/` my paths go straight to `Android`, `DCIM`, `Music`, etc. I don't see `mnt/sdcard`. If I saw `mnt`, I would try to navigate to the ID of the external SD card. Is this a bug in KDE Connect? It seems different from the one @OzymandiasTheGreat mentions since I can't see the external SD card.

**Comment by Bajoja** [comment]
@willsALMANJ indicator-kdeconnect only open the path that KDEConnect referer to stfp, so we can do nothing about this on indicator-kdeconnect

**Comment by willsALMANJ** [comment]
I have since re-flashed my phone with Lineage OS, so I have the most recent Lineage OS, kdeconnect app, kdeconnect client for Linux, and indicator-kdeconnect. Interestingly, I now see behavior similar to the bug that @OzymandiasTheGreat referenced and described by some posts in #10. I'm not sure which component mattered here, but something caused kdeconnect to switch from mounting `/storage/emulated/0` (what I was seeing before where I was being taken straight to the folder with Android, Music, DCIM, etc.) to mounting `/`, so now I can descend to both the internal and external SD card mount points, though they don't appear initially due to permissions issues (I have put in the path to those mounts as described elsewhere).

**Comment by Bajoja** [comment]
@willsALMANJ what's the name of your SD Card?
for example open your file manager and check properties of any file on the SD Card, and tell me the name that the SD Card is mounted.

I'm working on something in the branch dev and i need to now if the name of the SD Card is the same on differrent phones.

**Comment by willsALMANJ** [comment]
Mine is 9712-1E18. This matches the UUID that is shown when I run `blkid` as root. I found [this post](https://android.stackexchange.com/questions/135308/android-6-update-changed-sd-card-name) which isn't very authoritative but presents the same conclusion. I think the names of the volumes probably needs to be determined by the app, possibly by using [the getStorageVolumes function](https://developer.android.com/reference/android/os/storage/StorageManager.html#getStorageVolumes()).

Off topic question for you -- is there a simple way to start the sshfs mount with a script, either using kdeconnect-cli or a dbus command? I'd like to write a script to mount the phone and backup files. I think I can figure something out from the code in this repo, but I'm not very familiar with vala or dbus.

**Comment by Bajoja** [comment]
Yah, is possible, indicator-kdeconnect use dbus to mount it
