### ISSUE TITLE
Please provide a monochrome icon for the indicator

### ISSUE THREAD

**Issue by uncertainquark** [Bajoja/indicator-kdeconnect#69]
Here is how it looks now.

![screenshot from 2017-05-11 09 02 39](https://cloud.githubusercontent.com/assets/22585732/25933367/c3ce79ce-3633-11e7-96a9-5493c61cd0df.png)
Screenshot in elementary OS

Here is how the monochrome looks from another indicator (https://github.com/vikoadi/indicator-kdeconnect) that is no longer maintained but works.

![screenshot from 2017-05-11 10 17 27](https://cloud.githubusercontent.com/assets/22585732/25933394/0a6da79c-3634-11e7-94f7-10b8ec87466c.png)

Can you please provide a monochrome icon? It also has features like an exclamation mark when the pairing is not done.

**Comment by Bajoja** [comment]
Yeah, this is because the other developer focus on Elementary OS, I'm most focus on all DE, I'm not promise but maybe I will work in something to fix this.

**Comment by Bajoja** [comment]
Test the last commit and check if it work now.
Go to indicator-kdeconnect-settings and apply the option.
![elem](https://cloud.githubusercontent.com/assets/10621831/25969153/cbc22664-368b-11e7-829d-ca7b8a828bab.png)

**Comment by Bajoja** [comment]
@MrMarukesu, what about this?

**Comment by uncertainquark** [comment]
Yes it works, thank you. Waiting for it to be pushed in a new release. :)

**Comment by uncertainquark** [comment]
Hey, there is no need for a separate elementary icon setting as the default icon is monochrome now. SO you can remove that option from the settings :)
