### ISSUE TITLE
Ubuntu PPA package not found

### ISSUE THREAD

**Issue by segmentationfaulter** [Bajoja/indicator-kdeconnect#70]
I am getting this when I add the ubuntu PPA and run `sudo apt update`

```
W: Failed to fetch http://ppa.launchpad.net/webupd8team/indicator-kdeconnect/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/webupd8team/indicator-kdeconnect/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
```

What could be the issue?

**Comment by Bajoja** [comment]
I don't know, the maintainer have been disappeared and he is the only that can say what's going on.

**Comment by Bajoja** [comment]
@segmentationfaulter, you solve the problem? can i close this?

**Comment by segmentationfaulter** [comment]
@Bajoja you can close it if you wish so, but it is still giving me the same error even after removing and adding again.

**Comment by Bajoja** [comment]
What Distribution are you using?

**Comment by segmentationfaulter** [comment]
Ubuntu 14.04.

**Comment by segmentationfaulter** [comment]
sorry, I didn't notice, there is no support for 14.04, closing it.

**Comment by Bajoja** [comment]
Yeah, this is the first question that I was to ask you.
