### ISSUE TITLE
requests_oauthlib dependency missing in OBS openSUSE (Tumbleweed)

### ISSUE THREAD

**Issue by EarthlingKira** [Bajoja/indicator-kdeconnect#71]
When sending SMS the following error appears:

`Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 19, in <module>
    from requests_oauthlib import OAuth2Session
ModuleNotFoundError: No module named 'requests_oauthlib'`

**Comment by XenonPK** [comment]
I have already sent a request to include this package in Tumbleweed, it's only a matter of time until it gets accepted, you can check the status [here](https://build.opensuse.org/request/show/493394).

**Comment by Bajoja** [comment]
@EarthlingKira it's what @XenonPK  say, the problem is the package for python 3 is not available on Open Suse, just the package for python 2, i'm waiting for it's acceptance, otherwise the package, can be built on OpenSuse build service.

**Comment by EarthlingKira** [comment]
True, that's why I added the package via the devel python repo, this should fix the issue

**Comment by Bajoja** [comment]
OpenSuse build is down for maintenance so can't test it right now, but when is up and if everything compiled I accept the pull request

**Comment by Bajoja** [comment]
@XenonPK @EarthlingKira the status of the package goes to accepted so the aggregate file is no more necessary

**Comment by EarthlingKira** [comment]
@Bajoja You are right about Tumbleweed. But people using openSUSE 42.2 and openSUSE 42.3 will still need the aggregate file

**Comment by Bajoja** [comment]
@EarthlingKira thanks for the advice

**Comment by Bajoja** [comment]
@EarthlingKira if i use the aggregate file that you provide compilation for Fedora on OBS breaks.
