### ISSUE TITLE
Sending sms broken

### ISSUE THREAD

**Issue by Driesm** [Bajoja/indicator-kdeconnect#76]
First of all this indicator is awsome! 
But my sms won't work anymore. It doesn't open when I click 'sent sms'
I searched on the web and for some this is solved possibly. Can't get it to work on my system (elementary os)

**Comment by Bajoja** [comment]
Thanks, open a monitor task and kill indicator-kdeconnect, then open a terminal and type "indicator-kdeconnect" to start it but with log on the terminal, then execute the send sms and post the log error here.

**Comment by Driesm** [comment]
Thanks for you awnser! How do I do this? I did:

> killall indicator-kdeconnect
> sudo indicator-kdeconnect
> 

and I get this:
 
> ** (indicator-kdeconnect:4752): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-veCp4c8qzE: Verbinding is geweigerd
> 
> (indicator-kdeconnect:4752): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
> 
> (indicator-kdeconnect:4752): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
> 
> (indicator-kdeconnect:4752): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
> ** Message: KDEConnectManager.vala:33: KDE Connect daemon found
> ** Message: KDEConnectManager.vala:47: Fout bij het openen van bestand ‘/tmp/devices’: Bestand bestaat al
> ** Message: Device.vala:103: device : /modules/kdeconnect/devices/b50a8e38e48e19f1
> ** Message: DeviceIndicator.vala:328: File path exist '/tmp/devices'
> 
> ** Message: DeviceIndicator.vala:340: Delete status found on file - OnePlus One : b50a8e38e48e19f1
> 

Also I'm running from this ppa: sudo add-apt-repository ppa:varlesh-l/indicator-kdeconnect.
This is the latest version?

**Comment by Bajoja** [comment]
No, the varlesh ppa is no more the last, check the readme and add the new ppa

**Comment by Driesm** [comment]
```
** (indicator-kdeconnect:13553): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-veCp4c8qzE: Verbinding is geweigerd

(indicator-kdeconnect:13553): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(indicator-kdeconnect:13553): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(indicator-kdeconnect:13553): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
** Message: KDEConnectManager.vala:33: KDE Connect daemon found
** Message: KDEConnectManager.vala:47: Fout bij het openen van bestand ‘/tmp/devices’: Bestand bestaat al
** Message: Device.vala:103: device : /modules/kdeconnect/devices/b50a8e38e48e19f1
** Message: DeviceIndicator.vala:274: File path exist '/tmp/devices'

** Message: DeviceIndicator.vala:315: Fout bij het verwijderen van bestand: Bewerking niet toegestaan

Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 17, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```
Alright, I have the same problems

**Comment by Bajoja** [comment]
You are using the ppa on the readme?

**Comment by Driesm** [comment]
Yep 

```
sudo add-apt-repository ppa:webupd8team/indicator-kdeconnect
sudo apt update
sudo apt install kdeconnect indicator-kdeconnect
```
then 

`sudo apt update && sudo apt upgrade`

**Comment by Bajoja** [comment]
and you reboot the machine?

**Comment by Driesm** [comment]
I did now. 
On reboot I got this
`
De bladwijzers konden niet in /home/dries/.local/share/user-places.xbel worden opgeslagen. De foutmelding die het systeem gaf was: Existing file /home/dries/.local/share/user-places.xbel is not writable. Deze foutmelding wordt slechts éénmaal getoond. Probeer de fout zo vlug mogelijk te verhelpen; meestal is de oorzaak van deze melding een vol geraakte schijf of partitie.
`
Sorry it's in dutch. Translated it more or less:

`The bookmark could not be saved in /home/dries/.local/share/user-places.xbel. The eroor the system gave was Existing file /home/dries/.local/share/user-places.xbel is not writable. This error wil be showed only once, Try to repair the error asap. Then something about my harddisk/partition being too full (it's not)
`

** (indicator-kdeconnect:4984): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-tgDsXKGlV1: Verbinding is geweigerd

(indicator-kdeconnect:4984): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(indicator-kdeconnect:4984): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(indicator-kdeconnect:4984): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
** Message: KDEConnectManager.vala:33: KDE Connect daemon found
** Message: KDEConnectManager.vala:47: Fout bij het openen van bestand ‘/tmp/devices’: Bestand bestaat al
** Message: Device.vala:103: device : /modules/kdeconnect/devices/b50a8e38e48e19f1
** Message: DeviceIndicator.vala:274: File path exist '/tmp/devices'

** Message: DeviceIndicator.vala:288: Status found on file - OnePlus One : b50a8e38e48e19f1

Tried the same thing and opening the files of the phone and got this

```
Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 17, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
[INFO 21:35:35.972092] Application.vala:153: Bestanden version: 0.3.4
[INFO 21:35:35.972190] Application.vala:155: Kernel version: 4.11.0-041100-generic
[WARNING 21:35:35.991547] Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-tgDsXKGlV1: Verbinding is geweigerd
[WARNING 21:35:36.003998] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 21:35:36.004059] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 21:35:36.004120] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[INFO 21:35:36.028853] Application.vala:82: Report any issues/bugs you might find to http://bugs.launchpad.net/pantheon-files
[WARNING 21:35:36.324432] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 21:35:36.451649] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 21:35:36.452034] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 21:35:36.452374] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 21:35:36.452428] AbstractDirectoryView.vala:3439: Could not set file attributes - Fout bij opslaan van bestandsmetadata: Kan boom van metagegevens niet openen


```

**Comment by Bajoja** [comment]
Seems you are missing the Notify package.
Try to install this "sudo apt-get install python-gobject"
and this "sudo apt-get install libnotify-bin"

**Comment by Driesm** [comment]
I am missing the second one but it I can't install. Maybe I removed the wrong ppa?

**Comment by Bajoja** [comment]
Umh, i'm not into Elementary OS things but try use "apt-cache search keyword" to search "libnotify" related packages.

**Comment by Driesm** [comment]
I made a mistake in the last one. Sorry. It's installed already. I do get notifications too. Also from KDE-connect. My texts show up on my pc. I just can't awnser

**Comment by Bajoja** [comment]
It working now?

**Comment by Driesm** [comment]
```
** (indicator-kdeconnect:8649): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-tgDsXKGlV1: Verbinding is geweigerd

(indicator-kdeconnect:8649): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(indicator-kdeconnect:8649): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(indicator-kdeconnect:8649): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
** Message: KDEConnectManager.vala:33: KDE Connect daemon found
** Message: KDEConnectManager.vala:47: Fout bij het openen van bestand ‘/tmp/devices’: Bestand bestaat al
** Message: Device.vala:103: device : /modules/kdeconnect/devices/b50a8e38e48e19f1
** Message: DeviceIndicator.vala:274: File path exist '/tmp/devices'

** Message: DeviceIndicator.vala:288: Status found on file - OnePlus One : b50a8e38e48e19f1

Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 17, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
[INFO 22:01:04.213869] Application.vala:153: Bestanden version: 0.3.4
[INFO 22:01:04.213951] Application.vala:155: Kernel version: 4.11.0-041100-generic
[WARNING 22:01:04.240184] Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-tgDsXKGlV1: Verbinding is geweigerd
[WARNING 22:01:04.246264] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 22:01:04.246303] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 22:01:04.246350] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[INFO 22:01:04.266773] Application.vala:82: Report any issues/bugs you might find to http://bugs.launchpad.net/pantheon-files
[WARNING 22:01:04.473475] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 22:01:04.592321] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 22:01:04.592789] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 22:01:04.593127] [GVFS] can't init metadata tree /home/dries/.local/share/gvfs-metadata/root: open: Toegang geweigerd
[WARNING 22:01:04.593195] AbstractDirectoryView.vala:3439: Could not set file attributes - Fout bij opslaan van bestandsmetadata: Kan boom van metagegevens niet openen


```

Nope, still the same problem

**Comment by Bajoja** [comment]
Sorry lets see if someone with Elementary can help you beacause i don't know the the name of notify package for you distro.

**Comment by Bajoja** [comment]
@Driesm any news about this?

**Comment by Driesm** [comment]
No change for me. Not much response on reddit either. Only one person who didn't have the same problem.

**Comment by Bajoja** [comment]
So you are the only one?

**Comment by Bajoja** [comment]
@Driesm try to install this package, "python3-gi"

**Comment by Bajoja** [comment]
Try this "sudo apt install gir1.2-notify-0.7"

**Comment by silmeth** [comment]
Encountered the same problem on Kubuntu 17.04 with `indicator-kdeconnect=0.9.2-1~webupd8~zesty0`. Installing `gir1.2-notify-0.7` fixed it.

**Comment by saurabh7481** [comment]
Installing this package - 'sudo apt install gir1.2-notify-0.7', now allows me to compose sms on elementary os.
