### ISSUE TITLE
Not apply language

### ISSUE THREAD

**Issue by varlesh** [Bajoja/indicator-kdeconnect#8]
**mo** installed to `/usr/share/locale/ru_RU/LC_MESSAGES/indicator-kdeconnect.mo`
But use English :(
log:
```
alex@dell:~$ indicator-kdeconnect
** Message: KDEConnectManager.vala:32: KDE Connect daemon found
** Message: Device.vala:93: device : /modules/kdeconnect/devices/4b32126eef8f0edb
** Message: Device.vala:93: device : /modules/kdeconnect/devices/f470ee0d8100f362

```

**Comment by varlesh** [comment]
oops, sorry it's my fault! All worked fine, i'm improperly select system locale.
![image](https://cloud.githubusercontent.com/assets/8083855/20607178/39703a36-b287-11e6-84dc-2b297665a3b1.png)

**Comment by Bajoja** [comment]
Yeah, when i was working on translations i have the same problem, i solved by the same way of you.
