### ISSUE TITLE
OBS repo does not offer the option the download the package for openSUSE.

### ISSUE THREAD

**Issue by nicber** [Bajoja/indicator-kdeconnect#80]
![screenshot of the issue](https://cloud.githubusercontent.com/assets/3106794/26756673/7913001e-487e-11e7-8f14-30f65022dd4c.png)

Only Fedora appears in the [download page](https://software.opensuse.org//download.html?project=home%3ABajoja&package=indicator-kdeconnect)

**Comment by Bajoja** [comment]
Thanks for the advice, already fixed

**Comment by nicber** [comment]
I get this warning when installing it:
`
(1/1) Installing: indicator-kdeconnect-0.9.0-25.1.x86_64 ...........................................................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/home_Bajoja/x86_64/indicator-kdeconnect-0.9.0-25.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID e1e09995: NOKEY
`

**Comment by Bajoja** [comment]
@nicber i will investigate that.
