### ISSUE TITLE
RFE: Method to display SMS Message History

### ISSUE THREAD

**Issue by derekatkins** [Bajoja/indicator-kdeconnect#84]
Hi,
It would be really nice if there were a way to view my SMS message history.  This would let me see previous messages sent and received to my various contacts, similar to what iMessage allows.  It would also allow me to send messages with the context in front of me, moreso than just an immediate SMS reply.  Moreover, it would give me context if I missed a message, and let me seamlessly switch back and forth between my phone and laptop.

**Comment by Bajoja** [comment]
This kind of feature need to be report to kdeconect developers, not indicator-kdeconnect.
