### ISSUE TITLE
 kdeconnect/indicator-kdeconnect commands?

### ISSUE THREAD

**Issue by DrAxelbauer** [Bajoja/indicator-kdeconnect#85]
Hi everyone!
I have a question. My plan is to use kaddressbook to send sms to my contacts via the command option. To do this i was searchin around if indicator-kdeconnect or kdeconnect has some kind of command line option to paste the command in external programs like kaddressbook. This would be fine, because then i don't have to copy/paste from kaddressbook to the indicator-kdeconnect pop-up window.
Any suggestions concerning this topic?

Best, Benjamin.

My specs:
Kubuntu 16.04
Plasma: 5.8.7
KDE Frameworks: 5.34.0
Ot: 5.6.1
kdeconnect: 1.0.3ubuntu16.04
indicator-kdeconnect: 0.6ubuntu16.04.1 

Does anyone here know about such a command or a different solution? 

See also [https://forum.kde.org/viewtopic.php?f=9&t=140685](url)

**Comment by Bajoja** [comment]
So you use KDE, why you need indicator-kdeconnect?

**Comment by DrAxelbauer** [comment]
I just removed the indicator app and now there is just the kdeconnect sign, but i don't see any option to send sms (in the option i already enabled the service to work on both sides (phone and computer)). Am I missing something?

**Comment by Bajoja** [comment]
kdeconnect on KDE only allow you to reply sms, not send them.
Send SMS on this indicator is an implemented feature.
