### ISSUE TITLE
Way to limit which notifications I receive?

### ISSUE THREAD

**Issue by derekatkins** [Bajoja/indicator-kdeconnect#87]
Is there a way to limit which notifications I receive on my KDE-Connect desktop?  For example, I definitely do not need my K-9 Mail notifications displayed; I already have local email notifications.  I probably don't need facebook notifications, either.  But I don't want to lose SMS notifications, so I'm afraid to turn off notifications en masse.

**Comment by Bajoja** [comment]
Indicator-kdeconnect don't manage notifications, so this kind of thing report to kdeconect developers.

**Comment by andyholmes** [comment]
@derekatkins I think the settings you're looking for is in the Android App->Plugins->Notifications, it's a really long list.
