### ISSUE TITLE
Submit package into Debian?

### ISSUE THREAD

**Issue by hyiltiz** [Bajoja/indicator-kdeconnect#91]
Debian users are usually advised not to install software through PPA, as it easily breaks the package dependency in the system (especially after several upgrades of the whole system, which happens quite frequently for a desktop user). That also holds true for most Debian-based distros. 

Alternatively, pushing the package into Debian packages can solve this issue. Not only that, it would make the package a universal accessibility as most Debian-based distributions grab their packages from Debian sources. 

So, would you like to package for Debian? It seems not too complicated, and if you are short of men-power, I might consider volunteering for that.

**Comment by Bajoja** [comment]
Hi, have this on Debian repository would be great, but I don't know how and at this time I can do this, so feel free to help packing it, and let me know if I can do something, or make a pull request with your changes if you modify the debian folder on the project.
