### ISSUE TITLE
no tray notification on Arch linux with Gnome

### ISSUE THREAD

**Issue by jeroen7s** [Bajoja/indicator-kdeconnect#94]
installing the indicator using the arch user repository works fine, but i can't seem to get the notification running.
i'm using manjaro (arch linux based) with gnome 3.24.2
wayland fix script seems to help, but needed a reboot instead of a logout to work.
anyway, can be closed

**Comment by jeroen7s** [comment]
running gnome in x11 instead of wayland doesn't help either
what is so different about this from other indicators that make this one broken and others not?

**Comment by Bajoja** [comment]
Yah, if you use wayland you have to use the script

**Comment by jeroen7s** [comment]
not sure if intended but the tray icon seems to disappear sometimes, if i take my android device and use remote input or send files or something it comes back

**Comment by Bajoja** [comment]
That's because your Android probably have a set a option to save power

**Comment by andyholmes** [comment]
@Bajoja I wonder have you noticed that sometimes a device will be "unreachable" and even report no plugins in device->loadedPlugins(), but still receives battery signals?

**Comment by Bajoja** [comment]
@andyholmes, I notice that, but just with some devices, and i'm not sure why that happen.

**Comment by andyholmes** [comment]
@Bajoja Okay, at least it's not jsut me. I think Gnome won't accept my extension if there's signals floating around like that, so i'll have to destroy it when unreachable. Thanks for letting me bug you for tips!

**Comment by Bajoja** [comment]
@andyholmes, When i have time i will test your extension, seems interesting.

**Comment by andyholmes** [comment]
@Bajoja Thanks, I'd appreciate your input. My extension is really Gnome specific, so I don't expect it to replace yours for anyone but full-Gnome users. My version of sms for example relies on gnome-online-accounts to get contacts instead of direct from Google, but maybe you can use parts of that as an option in Sms.py. I'd be happy to help with that if you want.

**Comment by jeroen7s** [comment]
@andyholmes that might be more than a few people, now that ubuntu is going to ditch unity in favor of gnome
