### ISSUE TITLE
Uses the Dbus Interface to send sms

### ISSUE THREAD

**Issue by MrMarukesu** [Bajoja/indicator-kdeconnect#97]
the actual method fail if the user uses the kdeconnect flatpak because the diferent nomeclature and the  `flatpak run --comand="kdeconnect-cli" org.kde.kdeconnect` don't run any variable, only show the help message.
so using the dbus interface directly allows send sms from both flatpak and non-sandboxed kdeconnect.

**Comment by Bajoja** [comment]
@MrMarukesu the Sms.py is executed by terminal, that is a problem or just the act of send SMS?

**Comment by MrMarukesu** [comment]
just sending the sms, the sms.py run correctly

**Comment by andyholmes** [comment]
Submitted PR #98

**Comment by Bajoja** [comment]
@MrMarukesu check the merge from #98 and give any feedback.

**Comment by MrMarukesu** [comment]
sms works now, thanks.

**Comment by Bajoja** [comment]
@MrMarukesu so when it's finished, feel free to make a pull request with your work.
