### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by pshem** [Bajoja/indicator-kdeconnect#99]
I did the Polish translation for the project a few weeks back and I'm now reviewing it to see if I can make any improvements. I'd like to point out a few inconsistencies in how the strings are used, and inquire about possible polishing of the source strings. Here are some of the issues that were noticeable:

1. Capitalization:

-  KDE Connect is written in multiple ways: KDE Connect(Strings 5, 11 and 14), KDEConnect(String 52), kdeconnect(String 53)

-  there are random capital letters in the middle of a string(Strings 4, 27-30 and 49).
I chose to preserve the source capitalization in my translation(with the exception of string 52, which is clearly a spelling mistake), but unless it makes sense(for CLI command suggestions for example, where kdeconnect is an actual command and writing it from a capital would make the command fail), I'd like to see them uniformed. 
In cases where preserving a different formatting is necessary, if would be very useful for translators if there were notes about it. I know weblate uses something called "source notes", which you can see for example in this translation for [F-Droid](https://hosted.weblate.org/translate/f-droid/fdroiddata/pl/?checksum=6d138a63aba6b8a9)

2. missing mention of F-Droid as a source for KDE Connect download(String 6).
F-Droid is one of the [three official sources](https://community.kde.org/KDEConnect#Installation) you can download the android part of KDE Connect from, along with Google Play Store and the source code. As KDE Connect Indicator is also open source, I believe it should promote the only public open-source Android repository, and have added a mention of it to the Polish translation.
@comradekingu, who did the Norwegian translation, seems to agree, as his translation also mentions F-Droid.

3. Missing plurals and "a"/"an". For example string 4 currently says:

> If you have Firewall running, please open port 1714-1764 for TCP and UDP

The correct form should be: 

> If you have a Firewall running, please open ports 1714-1764 for TCP and UDP

If I were to improve the original and not just fix it, I'd make it read:

> If you have a firewall running, please open TCP and UDP ports 1714-1764

4. This is not a mistake, just something that bugs me: punctuation, especially '.' at the end of strings. I'm not an English native, and I'd really appreciate if one chimed in on the topic. 
Since my initial translation, hosted weblate has started enforcing formatting similarity, ie. translations of source strings that end with a '.' have to end with a '.' too. In a lot of the strings, the '.' at the end feels forced and artificial(Strings: 7, 11, 38, 39)

5. I would also appreciate guidance on whether "Indicator" in the name of the application should be translated. So far, I've left it untranslated. This is mainly relevant for string 12

I'm not sure what to suggest at this point, as many translations have been made and it would be a waste to have them disappear only because of formatting changes, which other translators may have already adjusted in their translations. If you agree, I could make an English(GB) translation showing how I think most of the source strings should look like. 

I would appreciate if other translators chimed in, so I'm mentioning everyone I identified from the .po merge commits:
@vdragon, @slsimic, @png2378, @vistaus, @welaq, @ShellAddicted, @BathoryPeter, @muzena, @iota-dev, @fitojb, @thomazio, @p-bo, @victorenator

**Comment by Bajoja** [comment]
@pshem, i agree with you, so you make changes on the main pot file, and submit your changes as pull request, then we can the source strings should look like.

**Comment by pshem** [comment]
Ok, I'll try to have it done by next weekend
